// Hablo phrase library. Content only — no logic.
// Array order = unlock order. ids are stable forever; append, never renumber.
// Latin American Spanish; no vosotros. Validated by test/phrases.test.js.
window.PHRASES = [
  // ---- Tier 1: survival essentials (p001–p055) ----
  { id: "p001", es: "Hola, ¿cómo estás?", en: "Hi, how are you?", cat: "greetings-basics", note: "informal" },
  { id: "p002", es: "Bien, gracias. ¿Y tú?", en: "Good, thanks. And you?", cat: "greetings-basics", note: "" },
  { id: "p003", es: "Mucho gusto.", en: "Nice to meet you.", cat: "greetings-basics", note: "" },
  { id: "p004", es: "Por favor.", en: "Please.", cat: "courtesy", note: "" },
  { id: "p005", es: "Gracias.", en: "Thank you.", cat: "courtesy", note: "" },
  { id: "p006", es: "De nada.", en: "You're welcome.", cat: "courtesy", note: "" },
  { id: "p007", es: "Perdón, no entiendo.", en: "Sorry, I don't understand.", cat: "greetings-basics", note: "" },
  { id: "p008", es: "¿Puedes hablar más despacio?", en: "Can you speak more slowly?", cat: "greetings-basics", note: "" },
  { id: "p009", es: "¿Cómo se dice esto en español?", en: "How do you say this in Spanish?", cat: "greetings-basics", note: "" },
  { id: "p010", es: "No hablo mucho español.", en: "I don't speak much Spanish.", cat: "greetings-basics", note: "" },
  { id: "p011", es: "¿Dónde está el baño?", en: "Where is the bathroom?", cat: "getting-around", note: "" },
  { id: "p012", es: "¿Cuánto cuesta?", en: "How much does it cost?", cat: "money-shopping", note: "" },
  { id: "p013", es: "Quisiera esto, por favor.", en: "I'd like this, please.", cat: "food-restaurants", note: "polite" },
  { id: "p014", es: "La cuenta, por favor.", en: "The check, please.", cat: "food-restaurants", note: "" },
  { id: "p015", es: "No sé.", en: "I don't know.", cat: "questions-connectors", note: "" },
  { id: "p016", es: "Buenos días.", en: "Good morning.", cat: "greetings-basics", note: "" },
  { id: "p017", es: "Buenas tardes.", en: "Good afternoon.", cat: "greetings-basics", note: "" },
  { id: "p018", es: "Buenas noches.", en: "Good evening. / Good night.", cat: "greetings-basics", note: "" },
  { id: "p019", es: "Adiós, hasta luego.", en: "Goodbye, see you later.", cat: "greetings-basics", note: "" },
  { id: "p020", es: "¿Qué tal?", en: "How's it going?", cat: "greetings-basics", note: "informal" },
  { id: "p021", es: "Me llamo Andy.", en: "My name is Andy.", cat: "greetings-basics", note: "" },
  { id: "p022", es: "¿Cómo te llamas?", en: "What's your name?", cat: "greetings-basics", note: "informal" },
  { id: "p023", es: "¿Habla inglés?", en: "Do you speak English?", cat: "greetings-basics", note: "polite (usted)" },
  { id: "p024", es: "Disculpe.", en: "Excuse me. (to get attention)", cat: "courtesy", note: "polite (usted)" },
  { id: "p025", es: "Con permiso.", en: "Excuse me. (passing by)", cat: "courtesy", note: "" },
  { id: "p026", es: "Lo siento.", en: "I'm sorry.", cat: "courtesy", note: "" },
  { id: "p027", es: "No hay problema.", en: "No problem.", cat: "courtesy", note: "" },
  { id: "p028", es: "Muchas gracias, muy amable.", en: "Thanks so much, very kind of you.", cat: "courtesy", note: "" },
  { id: "p029", es: "¡Salud!", en: "Bless you! / Cheers!", cat: "courtesy", note: "" },
  { id: "p030", es: "Bienvenido.", en: "Welcome.", cat: "courtesy", note: "" },
  { id: "p031", es: "¿Dónde está la estación?", en: "Where is the station?", cat: "getting-around", note: "" },
  { id: "p032", es: "¿Está cerca?", en: "Is it close?", cat: "getting-around", note: "" },
  { id: "p033", es: "A la derecha.", en: "To the right.", cat: "getting-around", note: "" },
  { id: "p034", es: "A la izquierda.", en: "To the left.", cat: "getting-around", note: "" },
  { id: "p035", es: "Todo derecho.", en: "Straight ahead.", cat: "getting-around", note: "LatAm; also 'derecho'" },
  { id: "p036", es: "Una mesa para dos, por favor.", en: "A table for two, please.", cat: "food-restaurants", note: "" },
  { id: "p037", es: "El menú, por favor.", en: "The menu, please.", cat: "food-restaurants", note: "" },
  { id: "p038", es: "Un agua, por favor.", en: "A water, please.", cat: "food-restaurants", note: "" },
  { id: "p039", es: "Está delicioso.", en: "It's delicious.", cat: "food-restaurants", note: "" },
  { id: "p040", es: "¿Aceptan tarjeta?", en: "Do you take cards?", cat: "money-shopping", note: "" },
  { id: "p041", es: "En efectivo.", en: "In cash.", cat: "money-shopping", note: "" },
  { id: "p042", es: "Es muy caro.", en: "It's very expensive.", cat: "money-shopping", note: "" },
  { id: "p043", es: "Sí, claro.", en: "Yes, of course.", cat: "questions-connectors", note: "" },
  { id: "p044", es: "Tal vez.", en: "Maybe.", cat: "questions-connectors", note: "" },
  { id: "p045", es: "¿Por qué?", en: "Why?", cat: "questions-connectors", note: "" },
  { id: "p046", es: "Porque sí.", en: "Just because.", cat: "questions-connectors", note: "" },
  { id: "p047", es: "¿Qué es esto?", en: "What is this?", cat: "questions-connectors", note: "" },
  { id: "p048", es: "¡Ayuda!", en: "Help!", cat: "emergencies-help", note: "" },
  { id: "p049", es: "Necesito ayuda.", en: "I need help.", cat: "emergencies-help", note: "" },
  { id: "p050", es: "¿Me puede ayudar?", en: "Can you help me?", cat: "emergencies-help", note: "polite (usted)" },
  { id: "p051", es: "No me siento bien.", en: "I don't feel well.", cat: "emergencies-help", note: "" },
  { id: "p052", es: "Soy de Estados Unidos.", en: "I'm from the United States.", cat: "smalltalk-you", note: "" },
  { id: "p053", es: "¿De dónde eres?", en: "Where are you from?", cat: "smalltalk-you", note: "informal" },
  { id: "p054", es: "Estoy aprendiendo español.", en: "I'm learning Spanish.", cat: "smalltalk-you", note: "" },
  { id: "p055", es: "Vivo en Pensilvania.", en: "I live in Pennsylvania.", cat: "smalltalk-you", note: "" },
];
