// Hablo phrase library. Content only — no logic.
// Array order = unlock order. ids are stable forever; append, never renumber.
// Latin American Spanish; no vosotros. Validated by test/phrases.test.js.
window.PHRASES = [
  // ---- Tier 1: survival essentials (p001–p055) ----
  { id: "p001", es: "Hola, ¿cómo estás?", en: "Hi, how are you?", cat: "greetings-basics", note: "informal" },
  { id: "p002", es: "Bien, gracias. ¿Y tú?", en: "Good, thanks. And you?", cat: "greetings-basics", note: "" },
  { id: "p003", es: "Mucho gusto.", en: "Nice to meet you.", cat: "greetings-basics", note: "" },
  { id: "p004", es: "Por favor.", en: "Please.", cat: "courtesy", note: "" },
  { id: "p005", es: "Gracias.", en: "Thank you.", cat: "courtesy", note: "" },
  { id: "p006", es: "De nada.", en: "You're welcome.", cat: "courtesy", note: "" },
  { id: "p007", es: "Perdón, no entiendo.", en: "Sorry, I don't understand.", cat: "greetings-basics", note: "" },
  { id: "p008", es: "¿Puedes hablar más despacio?", en: "Can you speak more slowly?", cat: "greetings-basics", note: "" },
  { id: "p009", es: "¿Cómo se dice esto en español?", en: "How do you say this in Spanish?", cat: "greetings-basics", note: "" },
  { id: "p010", es: "No hablo mucho español.", en: "I don't speak much Spanish.", cat: "greetings-basics", note: "" },
  { id: "p011", es: "¿Dónde está el baño?", en: "Where is the bathroom?", cat: "getting-around", note: "" },
  { id: "p012", es: "¿Cuánto cuesta?", en: "How much does it cost?", cat: "money-shopping", note: "" },
  { id: "p013", es: "Quisiera esto, por favor.", en: "I'd like this, please.", cat: "food-restaurants", note: "polite" },
  { id: "p014", es: "La cuenta, por favor.", en: "The check, please.", cat: "food-restaurants", note: "" },
  { id: "p015", es: "No sé.", en: "I don't know.", cat: "questions-connectors", note: "" },
  { id: "p016", es: "Buenos días.", en: "Good morning.", cat: "greetings-basics", note: "" },
  { id: "p017", es: "Buenas tardes.", en: "Good afternoon.", cat: "greetings-basics", note: "" },
  { id: "p018", es: "Buenas noches.", en: "Good evening. / Good night.", cat: "greetings-basics", note: "" },
  { id: "p019", es: "Adiós, hasta luego.", en: "Goodbye, see you later.", cat: "greetings-basics", note: "" },
  { id: "p020", es: "¿Qué tal?", en: "How's it going?", cat: "greetings-basics", note: "informal" },
  { id: "p021", es: "Me llamo Andy.", en: "My name is Andy.", cat: "greetings-basics", note: "" },
  { id: "p022", es: "¿Cómo te llamas?", en: "What's your name?", cat: "greetings-basics", note: "informal" },
  { id: "p023", es: "¿Habla inglés?", en: "Do you speak English?", cat: "greetings-basics", note: "polite (usted)" },
  { id: "p024", es: "Disculpe.", en: "Excuse me. (to get attention)", cat: "courtesy", note: "polite (usted)" },
  { id: "p025", es: "Con permiso.", en: "Excuse me. (passing by)", cat: "courtesy", note: "" },
  { id: "p026", es: "Lo siento.", en: "I'm sorry.", cat: "courtesy", note: "" },
  { id: "p027", es: "No hay problema.", en: "No problem.", cat: "courtesy", note: "" },
  { id: "p028", es: "Muchas gracias, muy amable.", en: "Thanks so much, very kind of you.", cat: "courtesy", note: "" },
  { id: "p029", es: "¡Salud!", en: "Bless you! / Cheers!", cat: "courtesy", note: "" },
  { id: "p030", es: "Bienvenido.", en: "Welcome.", cat: "courtesy", note: "" },
  { id: "p031", es: "¿Dónde está la estación?", en: "Where is the station?", cat: "getting-around", note: "" },
  { id: "p032", es: "¿Está cerca?", en: "Is it close?", cat: "getting-around", note: "" },
  { id: "p033", es: "A la derecha.", en: "To the right.", cat: "getting-around", note: "" },
  { id: "p034", es: "A la izquierda.", en: "To the left.", cat: "getting-around", note: "" },
  { id: "p035", es: "Todo derecho.", en: "Straight ahead.", cat: "getting-around", note: "LatAm; also 'derecho'" },
  { id: "p036", es: "Una mesa para dos, por favor.", en: "A table for two, please.", cat: "food-restaurants", note: "" },
  { id: "p037", es: "El menú, por favor.", en: "The menu, please.", cat: "food-restaurants", note: "" },
  { id: "p038", es: "Un agua, por favor.", en: "A water, please.", cat: "food-restaurants", note: "" },
  { id: "p039", es: "Está delicioso.", en: "It's delicious.", cat: "food-restaurants", note: "" },
  { id: "p040", es: "¿Aceptan tarjeta?", en: "Do you take cards?", cat: "money-shopping", note: "" },
  { id: "p041", es: "En efectivo.", en: "In cash.", cat: "money-shopping", note: "" },
  { id: "p042", es: "Es muy caro.", en: "It's very expensive.", cat: "money-shopping", note: "" },
  { id: "p043", es: "Sí, claro.", en: "Yes, of course.", cat: "questions-connectors", note: "" },
  { id: "p044", es: "Tal vez.", en: "Maybe.", cat: "questions-connectors", note: "" },
  { id: "p045", es: "¿Por qué?", en: "Why?", cat: "questions-connectors", note: "" },
  { id: "p046", es: "Porque sí.", en: "Just because.", cat: "questions-connectors", note: "" },
  { id: "p047", es: "¿Qué es esto?", en: "What is this?", cat: "questions-connectors", note: "" },
  { id: "p048", es: "¡Ayuda!", en: "Help!", cat: "emergencies-help", note: "" },
  { id: "p049", es: "Necesito ayuda.", en: "I need help.", cat: "emergencies-help", note: "" },
  { id: "p050", es: "¿Me puede ayudar?", en: "Can you help me?", cat: "emergencies-help", note: "polite (usted)" },
  { id: "p051", es: "No me siento bien.", en: "I don't feel well.", cat: "emergencies-help", note: "" },
  { id: "p052", es: "Soy de Estados Unidos.", en: "I'm from the United States.", cat: "smalltalk-you", note: "" },
  { id: "p053", es: "¿De dónde eres?", en: "Where are you from?", cat: "smalltalk-you", note: "informal" },
  { id: "p054", es: "Estoy aprendiendo español.", en: "I'm learning Spanish.", cat: "smalltalk-you", note: "" },
  { id: "p055", es: "Vivo en Pensilvania.", en: "I live in Pennsylvania.", cat: "smalltalk-you", note: "" },
  // ---- Tier 2: high-frequency everyday (p056–p170) ----
  { id: "p056", es: "¿Cómo está usted?", en: "How are you?", cat: "greetings-basics", note: "formal (usted)" },
  { id: "p057", es: "¿Qué pasa?", en: "What's up?", cat: "greetings-basics", note: "informal" },
  { id: "p058", es: "Igualmente.", en: "Likewise.", cat: "greetings-basics", note: "" },
  { id: "p059", es: "Hasta mañana.", en: "See you tomorrow.", cat: "greetings-basics", note: "" },
  { id: "p060", es: "Nos vemos.", en: "See you.", cat: "greetings-basics", note: "informal" },
  { id: "p061", es: "Que tengas un buen día.", en: "Have a good day.", cat: "courtesy", note: "informal" },
  { id: "p062", es: "¿Todo bien?", en: "Everything good?", cat: "greetings-basics", note: "informal" },
  { id: "p063", es: "Tanto tiempo sin verte.", en: "Long time no see.", cat: "greetings-basics", note: "informal" },
  { id: "p064", es: "Con gusto.", en: "Gladly. / My pleasure.", cat: "courtesy", note: "common LatAm 'you're welcome'" },
  { id: "p065", es: "No se preocupe.", en: "Don't worry.", cat: "courtesy", note: "polite (usted)" },
  { id: "p066", es: "Está bien, no pasa nada.", en: "It's fine, no big deal.", cat: "courtesy", note: "" },
  { id: "p067", es: "¿Puedo pasar?", en: "May I come in / get by?", cat: "courtesy", note: "" },
  { id: "p068", es: "Es muy amable.", en: "That's very kind of you.", cat: "courtesy", note: "polite (usted)" },
  { id: "p069", es: "Perdón por llegar tarde.", en: "Sorry for being late.", cat: "courtesy", note: "" },
  { id: "p070", es: "¿Le molesta si abro la ventana?", en: "Do you mind if I open the window?", cat: "courtesy", note: "polite (usted)" },
  { id: "p071", es: "Gracias por todo.", en: "Thanks for everything.", cat: "courtesy", note: "" },
  { id: "p072", es: "¿A qué te dedicas?", en: "What do you do for work?", cat: "smalltalk-you", note: "informal" },
  { id: "p073", es: "Tengo mi propia empresa.", en: "I have my own company.", cat: "smalltalk-you", note: "" },
  { id: "p074", es: "¿Tienes hermanos?", en: "Do you have siblings?", cat: "smalltalk-you", note: "informal" },
  { id: "p075", es: "Tengo un hermano.", en: "I have one brother.", cat: "smalltalk-you", note: "" },
  { id: "p076", es: "¿Cuántos años tienes?", en: "How old are you?", cat: "smalltalk-you", note: "informal" },
  { id: "p077", es: "Tengo treinta años.", en: "I'm thirty years old.", cat: "smalltalk-you", note: "" },
  { id: "p078", es: "¿Qué te gusta hacer?", en: "What do you like to do?", cat: "smalltalk-you", note: "informal" },
  { id: "p079", es: "Me gusta viajar.", en: "I like to travel.", cat: "smalltalk-you", note: "" },
  { id: "p080", es: "Me gusta mucho la comida mexicana.", en: "I really like Mexican food.", cat: "smalltalk-you", note: "" },
  { id: "p081", es: "¿Estás casado?", en: "Are you married?", cat: "smalltalk-you", note: "informal; casada to a woman" },
  { id: "p082", es: "¿Hablas otros idiomas?", en: "Do you speak other languages?", cat: "smalltalk-you", note: "informal" },
  { id: "p083", es: "Es la primera vez que vengo aquí.", en: "It's my first time here.", cat: "smalltalk-you", note: "" },
  { id: "p084", es: "Pero…", en: "But…", cat: "questions-connectors", note: "" },
  { id: "p085", es: "Entonces…", en: "So… / Then…", cat: "questions-connectors", note: "" },
  { id: "p086", es: "También.", en: "Also. / Too.", cat: "questions-connectors", note: "" },
  { id: "p087", es: "Yo también.", en: "Me too.", cat: "questions-connectors", note: "" },
  { id: "p088", es: "Yo no.", en: "Not me.", cat: "questions-connectors", note: "" },
  { id: "p089", es: "O sea…", en: "I mean… / In other words…", cat: "questions-connectors", note: "filler" },
  { id: "p090", es: "Es que…", en: "The thing is…", cat: "questions-connectors", note: "filler" },
  { id: "p091", es: "¿Qué significa esa palabra?", en: "What does that word mean?", cat: "questions-connectors", note: "" },
  { id: "p092", es: "¿Cómo?", en: "What? / Come again?", cat: "questions-connectors", note: "" },
  { id: "p093", es: "¿Dónde?", en: "Where?", cat: "questions-connectors", note: "" },
  { id: "p094", es: "¿Cuándo?", en: "When?", cat: "questions-connectors", note: "" },
  { id: "p095", es: "¿Quién?", en: "Who?", cat: "questions-connectors", note: "" },
  { id: "p096", es: "¿Cuál prefieres?", en: "Which do you prefer?", cat: "questions-connectors", note: "informal" },
  { id: "p097", es: "Por ejemplo…", en: "For example…", cat: "questions-connectors", note: "" },
  { id: "p098", es: "Además…", en: "Besides… / What's more…", cat: "questions-connectors", note: "" },
  { id: "p099", es: "Casi.", en: "Almost.", cat: "questions-connectors", note: "" },
  { id: "p100", es: "¿Dónde puedo tomar un taxi?", en: "Where can I get a taxi?", cat: "getting-around", note: "" },
  { id: "p101", es: "¿Me puede llevar a esta dirección?", en: "Can you take me to this address?", cat: "getting-around", note: "polite (usted)" },
  { id: "p102", es: "Aquí está bien, gracias.", en: "Right here is fine, thanks.", cat: "getting-around", note: "in a taxi" },
  { id: "p103", es: "¿Cuánto tiempo se tarda?", en: "How long does it take?", cat: "getting-around", note: "" },
  { id: "p104", es: "¿A qué hora sale?", en: "What time does it leave?", cat: "getting-around", note: "" },
  { id: "p105", es: "¿Dónde está la parada del autobús?", en: "Where is the bus stop?", cat: "getting-around", note: "" },
  { id: "p106", es: "Un boleto, por favor.", en: "One ticket, please.", cat: "getting-around", note: "LatAm: boleto" },
  { id: "p107", es: "¿Este autobús va al centro?", en: "Does this bus go downtown?", cat: "getting-around", note: "" },
  { id: "p108", es: "Estoy perdido.", en: "I'm lost.", cat: "getting-around", note: "perdida for women" },
  { id: "p109", es: "¿Me puede mostrar en el mapa?", en: "Can you show me on the map?", cat: "getting-around", note: "polite (usted)" },
  { id: "p110", es: "¿Dónde está el aeropuerto?", en: "Where is the airport?", cat: "getting-around", note: "" },
  { id: "p111", es: "Está muy lejos.", en: "It's very far.", cat: "getting-around", note: "" },
  { id: "p112", es: "A dos cuadras.", en: "Two blocks away.", cat: "getting-around", note: "LatAm: cuadras" },
  { id: "p113", es: "En la esquina.", en: "On the corner.", cat: "getting-around", note: "" },
  { id: "p114", es: "¿Puedo ir caminando?", en: "Can I walk there?", cat: "getting-around", note: "" },
  { id: "p115", es: "¿Dónde estamos?", en: "Where are we?", cat: "getting-around", note: "" },
  { id: "p116", es: "Necesito un hotel.", en: "I need a hotel.", cat: "getting-around", note: "" },
  { id: "p117", es: "¿Tiene una habitación disponible?", en: "Do you have a room available?", cat: "getting-around", note: "polite (usted)" },
  { id: "p118", es: "Para mí, los tacos.", en: "For me, the tacos.", cat: "food-restaurants", note: "" },
  { id: "p119", es: "¿Qué me recomienda?", en: "What do you recommend?", cat: "food-restaurants", note: "polite (usted)" },
  { id: "p120", es: "Sin cebolla, por favor.", en: "Without onion, please.", cat: "food-restaurants", note: "" },
  { id: "p121", es: "Con todo.", en: "With everything.", cat: "food-restaurants", note: "" },
  { id: "p122", es: "Una cerveza, por favor.", en: "A beer, please.", cat: "food-restaurants", note: "" },
  { id: "p123", es: "Un café con leche.", en: "A coffee with milk.", cat: "food-restaurants", note: "" },
  { id: "p124", es: "¿Está picante?", en: "Is it spicy?", cat: "food-restaurants", note: "" },
  { id: "p125", es: "No muy picante, por favor.", en: "Not too spicy, please.", cat: "food-restaurants", note: "" },
  { id: "p126", es: "Soy alérgico a los mariscos.", en: "I'm allergic to shellfish.", cat: "food-restaurants", note: "alérgica for women" },
  { id: "p127", es: "¿Qué lleva este plato?", en: "What's in this dish?", cat: "food-restaurants", note: "" },
  { id: "p128", es: "¿Nos trae más agua, por favor?", en: "Would you bring us more water, please?", cat: "food-restaurants", note: "polite (usted)" },
  { id: "p129", es: "Está muy rico.", en: "It's really tasty.", cat: "food-restaurants", note: "very LatAm" },
  { id: "p130", es: "¿Está incluida la propina?", en: "Is the tip included?", cat: "food-restaurants", note: "" },
  { id: "p131", es: "Para llevar, por favor.", en: "To go, please.", cat: "food-restaurants", note: "" },
  { id: "p132", es: "Para comer aquí.", en: "For here.", cat: "food-restaurants", note: "" },
  { id: "p133", es: "¿Tienen menú en inglés?", en: "Do you have an English menu?", cat: "food-restaurants", note: "" },
  { id: "p134", es: "Buen provecho.", en: "Enjoy your meal.", cat: "food-restaurants", note: "" },
  { id: "p135", es: "Otra ronda, por favor.", en: "Another round, please.", cat: "food-restaurants", note: "" },
  { id: "p136", es: "¿Cuánto le debo?", en: "How much do I owe you?", cat: "money-shopping", note: "polite (usted)" },
  { id: "p137", es: "¿Tiene cambio?", en: "Do you have change?", cat: "money-shopping", note: "polite (usted)" },
  { id: "p138", es: "Quédese con el cambio.", en: "Keep the change.", cat: "money-shopping", note: "polite (usted)" },
  { id: "p139", es: "Solo estoy mirando.", en: "I'm just looking.", cat: "money-shopping", note: "shopping" },
  { id: "p140", es: "¿Tiene esto en otra talla?", en: "Do you have this in another size?", cat: "money-shopping", note: "" },
  { id: "p141", es: "¿Me hace un descuento?", en: "Can you give me a discount?", cat: "money-shopping", note: "" },
  { id: "p142", es: "Me lo llevo.", en: "I'll take it.", cat: "money-shopping", note: "" },
  { id: "p143", es: "¿Dónde hay un cajero?", en: "Where's an ATM?", cat: "money-shopping", note: "cajero automático" },
  { id: "p144", es: "¿A cómo está el dólar?", en: "What's the dollar exchange rate?", cat: "money-shopping", note: "LatAm" },
  { id: "p145", es: "Es demasiado.", en: "That's too much.", cat: "money-shopping", note: "" },
  { id: "p146", es: "¿Está en oferta?", en: "Is it on sale?", cat: "money-shopping", note: "" },
  { id: "p147", es: "Una bolsa, por favor.", en: "A bag, please.", cat: "money-shopping", note: "" },
  { id: "p148", es: "¿Qué hora es?", en: "What time is it?", cat: "time-plans", note: "" },
  { id: "p149", es: "¿A qué hora abren?", en: "What time do you open?", cat: "time-plans", note: "" },
  { id: "p150", es: "¿A qué hora cierran?", en: "What time do you close?", cat: "time-plans", note: "" },
  { id: "p151", es: "Hoy no puedo.", en: "I can't today.", cat: "time-plans", note: "" },
  { id: "p152", es: "¿Mañana te queda bien?", en: "Does tomorrow work for you?", cat: "time-plans", note: "informal" },
  { id: "p153", es: "Ahora mismo.", en: "Right now.", cat: "time-plans", note: "" },
  { id: "p154", es: "Ahorita vengo.", en: "I'll be right back.", cat: "time-plans", note: "very LatAm" },
  { id: "p155", es: "Más tarde.", en: "Later.", cat: "time-plans", note: "" },
  { id: "p156", es: "Ya voy.", en: "I'm coming. / On my way.", cat: "time-plans", note: "" },
  { id: "p157", es: "Todavía no.", en: "Not yet.", cat: "time-plans", note: "" },
  { id: "p158", es: "¿Estás listo?", en: "Are you ready?", cat: "time-plans", note: "informal; lista to a woman" },
  { id: "p159", es: "Estoy listo.", en: "I'm ready.", cat: "time-plans", note: "" },
  { id: "p160", es: "No tengo tiempo.", en: "I don't have time.", cat: "time-plans", note: "" },
  { id: "p161", es: "Tengo prisa.", en: "I'm in a hurry.", cat: "time-plans", note: "" },
  { id: "p162", es: "Sin prisa.", en: "No rush.", cat: "time-plans", note: "" },
  { id: "p163", es: "¿Cuál es la contraseña del wifi?", en: "What's the wifi password?", cat: "daily-life", note: "" },
  { id: "p164", es: "No tengo señal.", en: "I have no signal.", cat: "daily-life", note: "" },
  { id: "p165", es: "Se me acabó la batería.", en: "My battery died.", cat: "daily-life", note: "" },
  { id: "p166", es: "¿Me presta su cargador?", en: "Could I borrow your charger?", cat: "daily-life", note: "polite (usted)" },
  { id: "p167", es: "Hace mucho calor.", en: "It's really hot out.", cat: "daily-life", note: "" },
  { id: "p168", es: "Hace frío.", en: "It's cold out.", cat: "daily-life", note: "" },
  { id: "p169", es: "Está lloviendo.", en: "It's raining.", cat: "daily-life", note: "" },
  { id: "p170", es: "¡Qué bonito día!", en: "What a beautiful day!", cat: "daily-life", note: "" },
  // ---- Tier 3: real conversation (p171–p315) ----
  { id: "p171", es: "¿Tienes hijos?", en: "Do you have kids?", cat: "smalltalk-you", note: "informal" },
  { id: "p172", es: "Tengo una novia.", en: "I have a girlfriend.", cat: "smalltalk-you", note: "" },
  { id: "p173", es: "¿Qué hiciste el fin de semana?", en: "What did you do over the weekend?", cat: "smalltalk-you", note: "informal" },
  { id: "p174", es: "Fui a la playa.", en: "I went to the beach.", cat: "smalltalk-you", note: "" },
  { id: "p175", es: "¿Cuánto tiempo llevas aquí?", en: "How long have you been here?", cat: "smalltalk-you", note: "informal" },
  { id: "p176", es: "Llevo una semana aquí.", en: "I've been here a week.", cat: "smalltalk-you", note: "" },
  { id: "p177", es: "¿Te gusta vivir aquí?", en: "Do you like living here?", cat: "smalltalk-you", note: "informal" },
  { id: "p178", es: "Me encanta este lugar.", en: "I love this place.", cat: "smalltalk-you", note: "" },
  { id: "p179", es: "¿Haces ejercicio?", en: "Do you work out?", cat: "smalltalk-you", note: "informal" },
  { id: "p180", es: "Voy al gimnasio casi todos los días.", en: "I go to the gym almost every day.", cat: "smalltalk-you", note: "" },
  { id: "p181", es: "Me lastimé la rodilla.", en: "I hurt my knee.", cat: "smalltalk-you", note: "" },
  { id: "p182", es: "Estoy de vacaciones.", en: "I'm on vacation.", cat: "smalltalk-you", note: "" },
  { id: "p183", es: "Estoy aquí por trabajo.", en: "I'm here for work.", cat: "smalltalk-you", note: "" },
  { id: "p184", es: "¿Cuál es tu comida favorita?", en: "What's your favorite food?", cat: "smalltalk-you", note: "informal" },
  { id: "p185", es: "¿Ves fútbol?", en: "Do you watch soccer?", cat: "smalltalk-you", note: "informal" },
  { id: "p186", es: "Soy fanático de los deportes.", en: "I'm a big sports fan.", cat: "smalltalk-you", note: "" },
  { id: "p187", es: "¿Qué música te gusta?", en: "What music do you like?", cat: "smalltalk-you", note: "informal" },
  { id: "p188", es: "No conozco esa canción.", en: "I don't know that song.", cat: "smalltalk-you", note: "" },
  { id: "p189", es: "¿Conoces un buen lugar por aquí?", en: "Do you know a good spot around here?", cat: "smalltalk-you", note: "informal" },
  { id: "p190", es: "Te presento a mi amigo.", en: "Let me introduce you to my friend.", cat: "smalltalk-you", note: "informal" },
  { id: "p191", es: "¿Nos tomamos una foto?", en: "Should we take a photo?", cat: "smalltalk-you", note: "" },
  { id: "p192", es: "Dame tu número.", en: "Give me your number.", cat: "smalltalk-you", note: "informal" },
  { id: "p193", es: "Aunque…", en: "Although…", cat: "questions-connectors", note: "" },
  { id: "p194", es: "Sin embargo…", en: "However…", cat: "questions-connectors", note: "slightly formal" },
  { id: "p195", es: "De hecho…", en: "Actually… / In fact…", cat: "questions-connectors", note: "" },
  { id: "p196", es: "Por eso…", en: "That's why…", cat: "questions-connectors", note: "" },
  { id: "p197", es: "Así que…", en: "So…", cat: "questions-connectors", note: "" },
  { id: "p198", es: "Mientras tanto…", en: "Meanwhile…", cat: "questions-connectors", note: "" },
  { id: "p199", es: "En vez de eso…", en: "Instead of that…", cat: "questions-connectors", note: "" },
  { id: "p200", es: "Sobre todo…", en: "Above all… / Especially…", cat: "questions-connectors", note: "" },
  { id: "p201", es: "Depende.", en: "It depends.", cat: "questions-connectors", note: "" },
  { id: "p202", es: "Más o menos.", en: "More or less. / So-so.", cat: "questions-connectors", note: "" },
  { id: "p203", es: "Claro que sí.", en: "Of course.", cat: "questions-connectors", note: "" },
  { id: "p204", es: "Claro que no.", en: "Of course not.", cat: "questions-connectors", note: "" },
  { id: "p205", es: "¿Verdad?", en: "Right?", cat: "questions-connectors", note: "tag question" },
  { id: "p206", es: "A ver…", en: "Let's see…", cat: "questions-connectors", note: "" },
  { id: "p207", es: "Me parece que sí.", en: "I think so.", cat: "opinions-reactions", note: "" },
  { id: "p208", es: "Me parece que no.", en: "I don't think so.", cat: "opinions-reactions", note: "" },
  { id: "p209", es: "Estoy de acuerdo.", en: "I agree.", cat: "opinions-reactions", note: "" },
  { id: "p210", es: "No estoy de acuerdo.", en: "I don't agree.", cat: "opinions-reactions", note: "" },
  { id: "p211", es: "Tienes razón.", en: "You're right.", cat: "opinions-reactions", note: "informal" },
  { id: "p212", es: "Tiene sentido.", en: "That makes sense.", cat: "opinions-reactions", note: "" },
  { id: "p213", es: "¿En serio?", en: "Seriously? / Really?", cat: "opinions-reactions", note: "" },
  { id: "p214", es: "¡No me digas!", en: "You don't say! / No way!", cat: "opinions-reactions", note: "" },
  { id: "p215", es: "¡Qué bueno!", en: "That's great!", cat: "opinions-reactions", note: "" },
  { id: "p216", es: "¡Qué pena!", en: "What a shame!", cat: "opinions-reactions", note: "" },
  { id: "p217", es: "¡Qué raro!", en: "How strange!", cat: "opinions-reactions", note: "" },
  { id: "p218", es: "Vale la pena.", en: "It's worth it.", cat: "opinions-reactions", note: "" },
  { id: "p219", es: "No vale la pena.", en: "It's not worth it.", cat: "opinions-reactions", note: "" },
  { id: "p220", es: "Me da igual.", en: "I don't care either way.", cat: "opinions-reactions", note: "" },
  { id: "p221", es: "¿Qué opinas?", en: "What do you think?", cat: "opinions-reactions", note: "informal" },
  { id: "p222", es: "¿Qué te pareció?", en: "What did you think of it?", cat: "opinions-reactions", note: "informal" },
  { id: "p223", es: "Me gustó mucho.", en: "I liked it a lot.", cat: "opinions-reactions", note: "" },
  { id: "p224", es: "No me gustó para nada.", en: "I didn't like it at all.", cat: "opinions-reactions", note: "" },
  { id: "p225", es: "Es mi favorito.", en: "It's my favorite.", cat: "opinions-reactions", note: "" },
  { id: "p226", es: "Está increíble.", en: "It's incredible.", cat: "opinions-reactions", note: "" },
  { id: "p227", es: "Podría ser mejor.", en: "It could be better.", cat: "opinions-reactions", note: "" },
  { id: "p228", es: "Fue una buena idea.", en: "It was a good idea.", cat: "opinions-reactions", note: "" },
  { id: "p229", es: "Tengo hambre.", en: "I'm hungry.", cat: "feelings-states", note: "" },
  { id: "p230", es: "Tengo sed.", en: "I'm thirsty.", cat: "feelings-states", note: "" },
  { id: "p231", es: "Tengo sueño.", en: "I'm sleepy.", cat: "feelings-states", note: "" },
  { id: "p232", es: "Tengo frío.", en: "I'm cold.", cat: "feelings-states", note: "" },
  { id: "p233", es: "Tengo calor.", en: "I'm hot.", cat: "feelings-states", note: "" },
  { id: "p234", es: "Estoy cansado.", en: "I'm tired.", cat: "feelings-states", note: "cansada for women" },
  { id: "p235", es: "Estoy emocionado.", en: "I'm excited.", cat: "feelings-states", note: "" },
  { id: "p236", es: "Estoy nervioso.", en: "I'm nervous.", cat: "feelings-states", note: "" },
  { id: "p237", es: "Estoy aburrido.", en: "I'm bored.", cat: "feelings-states", note: "" },
  { id: "p238", es: "Estoy ocupado.", en: "I'm busy.", cat: "feelings-states", note: "" },
  { id: "p239", es: "Estoy relajado.", en: "I'm relaxed.", cat: "feelings-states", note: "" },
  { id: "p240", es: "Me duele la cabeza.", en: "My head hurts.", cat: "feelings-states", note: "" },
  { id: "p241", es: "Me duele el estómago.", en: "My stomach hurts.", cat: "feelings-states", note: "" },
  { id: "p242", es: "Estoy enfermo.", en: "I'm sick.", cat: "feelings-states", note: "" },
  { id: "p243", es: "Me siento mucho mejor.", en: "I feel much better.", cat: "feelings-states", note: "" },
  { id: "p244", es: "Estoy feliz.", en: "I'm happy.", cat: "feelings-states", note: "" },
  { id: "p245", es: "Estoy un poco triste.", en: "I'm a little sad.", cat: "feelings-states", note: "" },
  { id: "p246", es: "No estoy de humor.", en: "I'm not in the mood.", cat: "feelings-states", note: "" },
  { id: "p247", es: "¿Tienen opciones vegetarianas?", en: "Do you have vegetarian options?", cat: "food-restaurants", note: "" },
  { id: "p248", es: "Quisiera reservar una mesa.", en: "I'd like to reserve a table.", cat: "food-restaurants", note: "" },
  { id: "p249", es: "¿Cuánto es la espera?", en: "How long is the wait?", cat: "food-restaurants", note: "" },
  { id: "p250", es: "Mi plato está frío.", en: "My dish is cold.", cat: "food-restaurants", note: "" },
  { id: "p251", es: "Esto no es lo que pedí.", en: "This isn't what I ordered.", cat: "food-restaurants", note: "" },
  { id: "p252", es: "¿Me trae la carta de vinos?", en: "Can I see the wine list?", cat: "food-restaurants", note: "polite (usted)" },
  { id: "p253", es: "Un vino tinto, por favor.", en: "A red wine, please.", cat: "food-restaurants", note: "" },
  { id: "p254", es: "Una botella de agua sin gas.", en: "A bottle of still water.", cat: "food-restaurants", note: "" },
  { id: "p255", es: "Con hielo, por favor.", en: "With ice, please.", cat: "food-restaurants", note: "" },
  { id: "p256", es: "Sin hielo, por favor.", en: "Without ice, please.", cat: "food-restaurants", note: "" },
  { id: "p257", es: "¿Qué postres tienen?", en: "What desserts do you have?", cat: "food-restaurants", note: "" },
  { id: "p258", es: "Estoy lleno.", en: "I'm full.", cat: "food-restaurants", note: "llena for women" },
  { id: "p259", es: "Todo estuvo excelente.", en: "Everything was excellent.", cat: "food-restaurants", note: "" },
  { id: "p260", es: "¿Puedo pagar con el teléfono?", en: "Can I pay with my phone?", cat: "food-restaurants", note: "" },
  { id: "p261", es: "¿Nos cobra por separado?", en: "Separate checks, please?", cat: "food-restaurants", note: "polite (usted)" },
  { id: "p262", es: "Es para compartir.", en: "It's to share.", cat: "food-restaurants", note: "" },
  { id: "p263", es: "¿A qué hora sirven el desayuno?", en: "What time do you serve breakfast?", cat: "food-restaurants", note: "" },
  { id: "p264", es: "¿Está incluido el desayuno?", en: "Is breakfast included?", cat: "food-restaurants", note: "" },
  { id: "p265", es: "¿Me puede pedir un taxi?", en: "Can you call me a taxi?", cat: "getting-around", note: "polite (usted)" },
  { id: "p266", es: "Voy a mi hotel.", en: "I'm going to my hotel.", cat: "getting-around", note: "" },
  { id: "p267", es: "Pare aquí, por favor.", en: "Stop here, please.", cat: "getting-around", note: "polite (usted)" },
  { id: "p268", es: "Siga derecho, por favor.", en: "Keep going straight, please.", cat: "getting-around", note: "polite (usted)" },
  { id: "p269", es: "¿Cuál es la mejor manera de llegar?", en: "What's the best way to get there?", cat: "getting-around", note: "" },
  { id: "p270", es: "¿Hay mucho tráfico?", en: "Is there a lot of traffic?", cat: "getting-around", note: "" },
  { id: "p271", es: "Perdí mi vuelo.", en: "I missed my flight.", cat: "getting-around", note: "" },
  { id: "p272", es: "¿Dónde recojo mi equipaje?", en: "Where do I pick up my luggage?", cat: "getting-around", note: "" },
  { id: "p273", es: "Mi maleta se perdió.", en: "My suitcase got lost.", cat: "getting-around", note: "" },
  { id: "p274", es: "¿Dónde está la salida?", en: "Where is the exit?", cat: "getting-around", note: "" },
  { id: "p275", es: "¿Dónde está la entrada?", en: "Where is the entrance?", cat: "getting-around", note: "" },
  { id: "p276", es: "Estoy buscando esta dirección.", en: "I'm looking for this address.", cat: "getting-around", note: "" },
  { id: "p277", es: "¿Me deja en la esquina?", en: "Can you drop me at the corner?", cat: "getting-around", note: "polite (usted)" },
  { id: "p278", es: "La próxima parada.", en: "The next stop.", cat: "getting-around", note: "" },
  { id: "p279", es: "¿Cuál es el precio final?", en: "What's the final price?", cat: "money-shopping", note: "" },
  { id: "p280", es: "¿Me da un recibo?", en: "Can I get a receipt?", cat: "money-shopping", note: "polite (usted)" },
  { id: "p281", es: "Me cobraron de más.", en: "They overcharged me.", cat: "money-shopping", note: "" },
  { id: "p282", es: "¿Puedo devolver esto?", en: "Can I return this?", cat: "money-shopping", note: "" },
  { id: "p283", es: "No funciona.", en: "It doesn't work.", cat: "money-shopping", note: "" },
  { id: "p284", es: "¿Tiene garantía?", en: "Does it have a warranty?", cat: "money-shopping", note: "" },
  { id: "p285", es: "Quiero cambiar dólares.", en: "I want to exchange dollars.", cat: "money-shopping", note: "" },
  { id: "p286", es: "¿Cuánto es en dólares?", en: "How much is that in dollars?", cat: "money-shopping", note: "" },
  { id: "p287", es: "Es una ganga.", en: "It's a bargain.", cat: "money-shopping", note: "" },
  { id: "p288", es: "¿Me lo puede envolver?", en: "Can you wrap it for me?", cat: "money-shopping", note: "polite (usted)" },
  { id: "p289", es: "¿Hay que pagar por adelantado?", en: "Do you have to pay in advance?", cat: "money-shopping", note: "" },
  { id: "p290", es: "Ya pagué.", en: "I already paid.", cat: "money-shopping", note: "" },
  { id: "p291", es: "¿Qué vas a hacer mañana?", en: "What are you doing tomorrow?", cat: "time-plans", note: "informal" },
  { id: "p292", es: "Vamos a salir esta noche.", en: "We're going out tonight.", cat: "time-plans", note: "" },
  { id: "p293", es: "¿Quieres venir con nosotros?", en: "Do you want to come with us?", cat: "time-plans", note: "informal" },
  { id: "p294", es: "Nos vemos a las ocho.", en: "See you at eight.", cat: "time-plans", note: "" },
  { id: "p295", es: "Llego en cinco minutos.", en: "I'll be there in five minutes.", cat: "time-plans", note: "" },
  { id: "p296", es: "Voy tarde.", en: "I'm running late.", cat: "time-plans", note: "" },
  { id: "p297", es: "Llegaste temprano.", en: "You're early.", cat: "time-plans", note: "informal" },
  { id: "p298", es: "¿Cuándo vuelves?", en: "When are you coming back?", cat: "time-plans", note: "informal" },
  { id: "p299", es: "Vuelvo la próxima semana.", en: "I'm coming back next week.", cat: "time-plans", note: "" },
  { id: "p300", es: "El lunes que viene.", en: "Next Monday.", cat: "time-plans", note: "" },
  { id: "p301", es: "Todos los días.", en: "Every day.", cat: "time-plans", note: "" },
  { id: "p302", es: "De vez en cuando.", en: "Once in a while.", cat: "time-plans", note: "" },
  { id: "p303", es: "Casi nunca.", en: "Almost never.", cat: "time-plans", note: "" },
  { id: "p304", es: "Casi siempre.", en: "Almost always.", cat: "time-plans", note: "" },
  { id: "p305", es: "Fue un día largo.", en: "It was a long day.", cat: "time-plans", note: "" },
  { id: "p306", es: "Necesito un médico.", en: "I need a doctor.", cat: "emergencies-help", note: "" },
  { id: "p307", es: "Llame a una ambulancia.", en: "Call an ambulance.", cat: "emergencies-help", note: "polite (usted)" },
  { id: "p308", es: "Llame a la policía.", en: "Call the police.", cat: "emergencies-help", note: "polite (usted)" },
  { id: "p309", es: "Es una emergencia.", en: "It's an emergency.", cat: "emergencies-help", note: "" },
  { id: "p310", es: "Me robaron.", en: "I got robbed.", cat: "emergencies-help", note: "" },
  { id: "p311", es: "Perdí mi pasaporte.", en: "I lost my passport.", cat: "emergencies-help", note: "" },
  { id: "p312", es: "Perdí mi teléfono.", en: "I lost my phone.", cat: "emergencies-help", note: "" },
  { id: "p313", es: "¿Dónde está la farmacia más cercana?", en: "Where's the nearest pharmacy?", cat: "emergencies-help", note: "" },
  { id: "p314", es: "Necesito medicina para el dolor.", en: "I need pain medicine.", cat: "emergencies-help", note: "" },
  { id: "p315", es: "Tenga cuidado.", en: "Be careful.", cat: "emergencies-help", note: "polite (usted)" },
  // ---- Tier 4: fluency glue + depth (p316–p500) ----
  { id: "p316", es: "La verdad es que…", en: "The truth is… / Honestly…", cat: "questions-connectors", note: "" },
  { id: "p317", es: "Lo que pasa es que…", en: "The thing is…", cat: "questions-connectors", note: "" },
  { id: "p318", es: "Por cierto…", en: "By the way…", cat: "questions-connectors", note: "" },
  { id: "p319", es: "En cambio…", en: "On the other hand…", cat: "questions-connectors", note: "" },
  { id: "p320", es: "Digamos…", en: "Let's say…", cat: "questions-connectors", note: "" },
  { id: "p321", es: "Bueno, pues…", en: "Well, then…", cat: "questions-connectors", note: "filler" },
  { id: "p322", es: "En realidad…", en: "Actually…", cat: "questions-connectors", note: "" },
  { id: "p323", es: "Al final…", en: "In the end…", cat: "questions-connectors", note: "" },
  { id: "p324", es: "Al principio…", en: "At first…", cat: "questions-connectors", note: "" },
  { id: "p325", es: "De todos modos…", en: "Anyway…", cat: "questions-connectors", note: "" },
  { id: "p326", es: "En cuanto a eso…", en: "As for that…", cat: "questions-connectors", note: "" },
  { id: "p327", es: "A propósito…", en: "Speaking of which…", cat: "questions-connectors", note: "" },
  { id: "p328", es: "Según él…", en: "According to him…", cat: "questions-connectors", note: "" },
  { id: "p329", es: "Es decir…", en: "That is to say…", cat: "questions-connectors", note: "" },
  { id: "p330", es: "Por lo menos…", en: "At least…", cat: "questions-connectors", note: "" },
  { id: "p331", es: "Por si acaso.", en: "Just in case.", cat: "questions-connectors", note: "" },
  { id: "p332", es: "Cuanto antes, mejor.", en: "The sooner the better.", cat: "questions-connectors", note: "" },
  { id: "p333", es: "Poco a poco.", en: "Little by little.", cat: "questions-connectors", note: "" },
  { id: "p334", es: "De repente…", en: "Suddenly…", cat: "questions-connectors", note: "" },
  { id: "p335", es: "Por fin.", en: "Finally.", cat: "questions-connectors", note: "" },
  { id: "p336", es: "Aun así…", en: "Even so…", cat: "questions-connectors", note: "" },
  { id: "p337", es: "O algo así.", en: "Or something like that.", cat: "questions-connectors", note: "" },
  { id: "p338", es: "Y así sucesivamente.", en: "And so on.", cat: "questions-connectors", note: "" },
  { id: "p339", es: "¿Y si vamos mañana?", en: "What if we go tomorrow?", cat: "questions-connectors", note: "" },
  { id: "p340", es: "Desde mi punto de vista…", en: "From my point of view…", cat: "opinions-reactions", note: "" },
  { id: "p341", es: "No estoy tan seguro.", en: "I'm not so sure.", cat: "opinions-reactions", note: "segura for women" },
  { id: "p342", es: "Puede ser.", en: "Could be.", cat: "opinions-reactions", note: "" },
  { id: "p343", es: "Sin duda.", en: "Without a doubt.", cat: "opinions-reactions", note: "" },
  { id: "p344", es: "Estoy convencido.", en: "I'm convinced.", cat: "opinions-reactions", note: "" },
  { id: "p345", es: "Para ser honesto…", en: "To be honest…", cat: "opinions-reactions", note: "" },
  { id: "p346", es: "Si te soy sincero…", en: "If I'm being honest with you…", cat: "opinions-reactions", note: "informal" },
  { id: "p347", es: "Me imagino que sí.", en: "I imagine so.", cat: "opinions-reactions", note: "" },
  { id: "p348", es: "Lo dudo.", en: "I doubt it.", cat: "opinions-reactions", note: "" },
  { id: "p349", es: "Ojalá.", en: "Hopefully. / I wish.", cat: "opinions-reactions", note: "very common" },
  { id: "p350", es: "¡Qué buena onda!", en: "How cool!", cat: "opinions-reactions", note: "very LatAm" },
  { id: "p351", es: "¡Qué padre!", en: "How cool!", cat: "opinions-reactions", note: "Mexico" },
  { id: "p352", es: "¡Genial!", en: "Awesome!", cat: "opinions-reactions", note: "" },
  { id: "p353", es: "¡Increíble!", en: "Incredible!", cat: "opinions-reactions", note: "" },
  { id: "p354", es: "¡Qué locura!", en: "That's crazy!", cat: "opinions-reactions", note: "" },
  { id: "p355", es: "¡Qué suerte!", en: "How lucky!", cat: "opinions-reactions", note: "" },
  { id: "p356", es: "¡Qué mala suerte!", en: "What bad luck!", cat: "opinions-reactions", note: "" },
  { id: "p357", es: "¡Felicidades!", en: "Congratulations!", cat: "opinions-reactions", note: "" },
  { id: "p358", es: "Te lo mereces.", en: "You deserve it.", cat: "opinions-reactions", note: "informal" },
  { id: "p359", es: "Estoy impresionado.", en: "I'm impressed.", cat: "opinions-reactions", note: "" },
  { id: "p360", es: "Me sorprendió.", en: "It surprised me.", cat: "opinions-reactions", note: "" },
  { id: "p361", es: "No me lo esperaba.", en: "I didn't expect that.", cat: "opinions-reactions", note: "" },
  { id: "p362", es: "Es un poco complicado.", en: "It's a bit complicated.", cat: "opinions-reactions", note: "" },
  { id: "p363", es: "No es para tanto.", en: "It's not a big deal.", cat: "opinions-reactions", note: "" },
  { id: "p364", es: "Mejor que nada.", en: "Better than nothing.", cat: "opinions-reactions", note: "" },
  { id: "p365", es: "Como quieras.", en: "Whatever you want.", cat: "opinions-reactions", note: "informal" },
  { id: "p366", es: "Buena idea.", en: "Good idea.", cat: "opinions-reactions", note: "" },
  { id: "p367", es: "Mala idea.", en: "Bad idea.", cat: "opinions-reactions", note: "" },
  { id: "p368", es: "Eso creo.", en: "I believe so.", cat: "opinions-reactions", note: "" },
  { id: "p369", es: "Que yo sepa, no.", en: "Not that I know of.", cat: "opinions-reactions", note: "" },
  { id: "p370", es: "Cambié de opinión.", en: "I changed my mind.", cat: "opinions-reactions", note: "" },
  { id: "p371", es: "Me convenciste.", en: "You convinced me.", cat: "opinions-reactions", note: "informal" },
  { id: "p372", es: "Estoy bromeando.", en: "I'm joking.", cat: "opinions-reactions", note: "" },
  { id: "p373", es: "Cuéntame más.", en: "Tell me more.", cat: "smalltalk-you", note: "informal" },
  { id: "p374", es: "¿Cómo te fue?", en: "How did it go?", cat: "smalltalk-you", note: "informal" },
  { id: "p375", es: "Me fue muy bien.", en: "It went really well.", cat: "smalltalk-you", note: "" },
  { id: "p376", es: "¿Qué has hecho últimamente?", en: "What have you been up to lately?", cat: "smalltalk-you", note: "informal" },
  { id: "p377", es: "Nada nuevo.", en: "Nothing new.", cat: "smalltalk-you", note: "" },
  { id: "p378", es: "¿Cómo está tu familia?", en: "How's your family?", cat: "smalltalk-you", note: "informal" },
  { id: "p379", es: "Saludos a tu familia.", en: "Say hi to your family.", cat: "smalltalk-you", note: "informal" },
  { id: "p380", es: "Hace mucho que no te veo.", en: "It's been a long time since I've seen you.", cat: "smalltalk-you", note: "informal" },
  { id: "p381", es: "Te ves muy bien.", en: "You look great.", cat: "smalltalk-you", note: "informal" },
  { id: "p382", es: "¿Sigues trabajando en lo mismo?", en: "Are you still doing the same work?", cat: "smalltalk-you", note: "informal" },
  { id: "p383", es: "Estoy pensando en mudarme.", en: "I'm thinking about moving.", cat: "smalltalk-you", note: "" },
  { id: "p384", es: "Quiero mejorar mi español.", en: "I want to improve my Spanish.", cat: "smalltalk-you", note: "" },
  { id: "p385", es: "¿Me corriges si me equivoco?", en: "Will you correct me if I make a mistake?", cat: "smalltalk-you", note: "informal" },
  { id: "p386", es: "¿Qué significa eso en inglés?", en: "What does that mean in English?", cat: "smalltalk-you", note: "" },
  { id: "p387", es: "Aprendí una palabra nueva hoy.", en: "I learned a new word today.", cat: "smalltalk-you", note: "" },
  { id: "p388", es: "Mi español está mejorando.", en: "My Spanish is getting better.", cat: "smalltalk-you", note: "" },
  { id: "p389", es: "Hablas muy rápido.", en: "You talk very fast.", cat: "smalltalk-you", note: "informal" },
  { id: "p390", es: "Estoy orgulloso de ti.", en: "I'm proud of you.", cat: "feelings-states", note: "informal" },
  { id: "p391", es: "Estoy agradecido.", en: "I'm grateful.", cat: "feelings-states", note: "" },
  { id: "p392", es: "Estoy estresado.", en: "I'm stressed.", cat: "feelings-states", note: "" },
  { id: "p393", es: "Estoy agotado.", en: "I'm exhausted.", cat: "feelings-states", note: "" },
  { id: "p394", es: "Estoy motivado.", en: "I'm motivated.", cat: "feelings-states", note: "" },
  { id: "p395", es: "Me siento como en casa.", en: "I feel at home.", cat: "feelings-states", note: "" },
  { id: "p396", es: "Extraño mi casa.", en: "I miss home.", cat: "feelings-states", note: "LatAm: extrañar" },
  { id: "p397", es: "Te extraño.", en: "I miss you.", cat: "feelings-states", note: "informal" },
  { id: "p398", es: "Estoy enamorado.", en: "I'm in love.", cat: "feelings-states", note: "" },
  { id: "p399", es: "Me asusté.", en: "I got scared.", cat: "feelings-states", note: "" },
  { id: "p400", es: "Me enojé.", en: "I got mad.", cat: "feelings-states", note: "LatAm: enojarse" },
  { id: "p401", es: "No te enojes.", en: "Don't get mad.", cat: "feelings-states", note: "informal" },
  { id: "p402", es: "Cálmate.", en: "Calm down.", cat: "feelings-states", note: "informal" },
  { id: "p403", es: "Tranquilo, todo va a estar bien.", en: "Relax, everything's going to be okay.", cat: "feelings-states", note: "" },
  { id: "p404", es: "Me da vergüenza.", en: "I'm embarrassed.", cat: "feelings-states", note: "" },
  { id: "p405", es: "¡Qué alivio!", en: "What a relief!", cat: "feelings-states", note: "" },
  { id: "p406", es: "Estoy de buen humor.", en: "I'm in a good mood.", cat: "feelings-states", note: "" },
  { id: "p407", es: "¡Cuánto tiempo!", en: "It's been ages!", cat: "greetings-basics", note: "" },
  { id: "p408", es: "¿Qué hay de nuevo?", en: "What's new?", cat: "greetings-basics", note: "" },
  { id: "p409", es: "Que te vaya bien.", en: "Take care. / Hope it goes well.", cat: "greetings-basics", note: "informal" },
  { id: "p410", es: "Cuídate mucho.", en: "Take good care of yourself.", cat: "greetings-basics", note: "informal" },
  { id: "p411", es: "Que descanses.", en: "Sleep well.", cat: "greetings-basics", note: "informal" },
  { id: "p412", es: "Nos estamos viendo.", en: "See you around.", cat: "greetings-basics", note: "very LatAm" },
  { id: "p413", es: "Fue un placer conocerte.", en: "It was a pleasure meeting you.", cat: "greetings-basics", note: "informal" },
  { id: "p414", es: "A la orden.", en: "At your service. / You're welcome.", cat: "greetings-basics", note: "common LatAm" },
  { id: "p415", es: "No quería molestarte.", en: "I didn't mean to bother you.", cat: "courtesy", note: "informal" },
  { id: "p416", es: "¿Te puedo hacer una pregunta?", en: "Can I ask you a question?", cat: "courtesy", note: "informal" },
  { id: "p417", es: "Te lo agradezco mucho.", en: "I really appreciate it.", cat: "courtesy", note: "informal" },
  { id: "p418", es: "Es un detalle muy lindo.", en: "That's a really sweet gesture.", cat: "courtesy", note: "" },
  { id: "p419", es: "Mi casa es tu casa.", en: "Make yourself at home.", cat: "courtesy", note: "" },
  { id: "p420", es: "Pásale.", en: "Come on in.", cat: "courtesy", note: "Mexico" },
  { id: "p421", es: "Se me antoja un taco.", en: "I'm craving a taco.", cat: "food-restaurants", note: "very LatAm: antojarse" },
  { id: "p422", es: "¿Pedimos algo?", en: "Should we order something?", cat: "food-restaurants", note: "" },
  { id: "p423", es: "Yo invito.", en: "It's on me.", cat: "food-restaurants", note: "" },
  { id: "p424", es: "La próxima invitas tú.", en: "Next one's on you.", cat: "food-restaurants", note: "informal" },
  { id: "p425", es: "¿Qué es lo más típico de aquí?", en: "What's the most typical local dish?", cat: "food-restaurants", note: "" },
  { id: "p426", es: "Quiero probar algo nuevo.", en: "I want to try something new.", cat: "food-restaurants", note: "" },
  { id: "p427", es: "Huele delicioso.", en: "It smells delicious.", cat: "food-restaurants", note: "" },
  { id: "p428", es: "¿Trae carne?", en: "Does it have meat?", cat: "food-restaurants", note: "" },
  { id: "p429", es: "Sin azúcar, por favor.", en: "No sugar, please.", cat: "food-restaurants", note: "" },
  { id: "p430", es: "Un jugo natural.", en: "A fresh juice.", cat: "food-restaurants", note: "LatAm: jugo" },
  { id: "p431", es: "Está muy salado.", en: "It's very salty.", cat: "food-restaurants", note: "" },
  { id: "p432", es: "Me encantó la comida.", en: "I loved the food.", cat: "food-restaurants", note: "" },
  { id: "p433", es: "Volveré pronto.", en: "I'll be back soon.", cat: "food-restaurants", note: "" },
  { id: "p434", es: "¿Está abierto hoy?", en: "Is it open today?", cat: "getting-around", note: "" },
  { id: "p435", es: "¿Hasta qué hora está abierto?", en: "Until what time is it open?", cat: "getting-around", note: "" },
  { id: "p436", es: "¿Vale la pena visitarlo?", en: "Is it worth visiting?", cat: "getting-around", note: "" },
  { id: "p437", es: "¿Me recomienda un lugar para visitar?", en: "Can you recommend a place to visit?", cat: "getting-around", note: "polite (usted)" },
  { id: "p438", es: "Quiero conocer la ciudad.", en: "I want to see the city.", cat: "getting-around", note: "" },
  { id: "p439", es: "¿Es seguro por aquí?", en: "Is it safe around here?", cat: "getting-around", note: "" },
  { id: "p440", es: "¿Es segura esta zona de noche?", en: "Is this area safe at night?", cat: "getting-around", note: "" },
  { id: "p441", es: "Tomemos el metro.", en: "Let's take the subway.", cat: "getting-around", note: "" },
  { id: "p442", es: "Bajamos en la próxima.", en: "We get off at the next one.", cat: "getting-around", note: "" },
  { id: "p443", es: "¿Cuánto cuesta la entrada?", en: "How much is admission?", cat: "getting-around", note: "" },
  { id: "p444", es: "¿Se puede tomar fotos?", en: "Can you take photos here?", cat: "getting-around", note: "" },
  { id: "p445", es: "La vista es hermosa.", en: "The view is beautiful.", cat: "getting-around", note: "" },
  { id: "p446", es: "¿Cuánto cuesta por noche?", en: "How much per night?", cat: "money-shopping", note: "" },
  { id: "p447", es: "¿Hay descuento si pago en efectivo?", en: "Is there a discount if I pay cash?", cat: "money-shopping", note: "" },
  { id: "p448", es: "Está bien de precio.", en: "That's a fair price.", cat: "money-shopping", note: "" },
  { id: "p449", es: "¿Me lo deja en cien?", en: "Would you take 100 for it?", cat: "money-shopping", note: "haggling" },
  { id: "p450", es: "Es mi última oferta.", en: "That's my final offer.", cat: "money-shopping", note: "" },
  { id: "p451", es: "Lo pienso y regreso.", en: "I'll think about it and come back.", cat: "money-shopping", note: "" },
  { id: "p452", es: "¿Dónde puedo comprar un recuerdo?", en: "Where can I buy a souvenir?", cat: "money-shopping", note: "" },
  { id: "p453", es: "¿Esto es hecho a mano?", en: "Is this handmade?", cat: "money-shopping", note: "" },
  { id: "p454", es: "Solo tengo un billete grande.", en: "I only have a large bill.", cat: "money-shopping", note: "" },
  { id: "p455", es: "¿Me puede dar cambio en billetes chicos?", en: "Can you give me change in small bills?", cat: "money-shopping", note: "polite (usted)" },
  { id: "p456", es: "La máquina no acepta mi tarjeta.", en: "The machine won't take my card.", cat: "money-shopping", note: "" },
  { id: "p457", es: "¿Cobran comisión?", en: "Do you charge a fee?", cat: "money-shopping", note: "" },
  { id: "p458", es: "¿Tienes planes para el sábado?", en: "Do you have plans for Saturday?", cat: "time-plans", note: "informal" },
  { id: "p459", es: "Estoy libre el domingo.", en: "I'm free on Sunday.", cat: "time-plans", note: "" },
  { id: "p460", es: "¿Lo dejamos para otro día?", en: "Can we leave it for another day?", cat: "time-plans", note: "" },
  { id: "p461", es: "Tuve que cancelar.", en: "I had to cancel.", cat: "time-plans", note: "" },
  { id: "p462", es: "Se me hizo tarde.", en: "I ran late.", cat: "time-plans", note: "LatAm" },
  { id: "p463", es: "Aún hay tiempo.", en: "There's still time.", cat: "time-plans", note: "" },
  { id: "p464", es: "Ya casi termino.", en: "I'm almost done.", cat: "time-plans", note: "" },
  { id: "p465", es: "Acabo de llegar.", en: "I just arrived.", cat: "time-plans", note: "" },
  { id: "p466", es: "Estoy a punto de salir.", en: "I'm about to leave.", cat: "time-plans", note: "" },
  { id: "p467", es: "Mientras esperamos…", en: "While we wait…", cat: "time-plans", note: "" },
  { id: "p468", es: "Desde hace dos años.", en: "For two years now.", cat: "time-plans", note: "" },
  { id: "p469", es: "Hace un rato.", en: "A little while ago.", cat: "time-plans", note: "" },
  { id: "p470", es: "Dentro de poco.", en: "In a little while.", cat: "time-plans", note: "" },
  { id: "p471", es: "A más tardar el viernes.", en: "By Friday at the latest.", cat: "time-plans", note: "" },
  { id: "p472", es: "Listo, nos coordinamos.", en: "Okay, we'll coordinate.", cat: "time-plans", note: "LatAm: listo = okay/done" },
  { id: "p473", es: "¡Cuidado!", en: "Watch out!", cat: "emergencies-help", note: "" },
  { id: "p474", es: "¡Llama a emergencias!", en: "Call emergency services!", cat: "emergencies-help", note: "informal" },
  { id: "p475", es: "Hubo un accidente.", en: "There was an accident.", cat: "emergencies-help", note: "" },
  { id: "p476", es: "Estoy herido.", en: "I'm hurt.", cat: "emergencies-help", note: "herida for women" },
  { id: "p477", es: "Tengo una condición médica.", en: "I have a medical condition.", cat: "emergencies-help", note: "" },
  { id: "p478", es: "Necesito ir al hospital.", en: "I need to go to the hospital.", cat: "emergencies-help", note: "" },
  { id: "p479", es: "¿Dónde está la embajada americana?", en: "Where is the American embassy?", cat: "emergencies-help", note: "" },
  { id: "p480", es: "Me siento mareado.", en: "I feel dizzy.", cat: "emergencies-help", note: "" },
  { id: "p481", es: "No puedo respirar bien.", en: "I can't breathe well.", cat: "emergencies-help", note: "" },
  { id: "p482", es: "Se me perdió la tarjeta.", en: "My card got lost.", cat: "emergencies-help", note: "" },
  { id: "p483", es: "Necesito hacer una llamada.", en: "I need to make a call.", cat: "emergencies-help", note: "" },
  { id: "p484", es: "Voy a lavar mi ropa.", en: "I'm going to do my laundry.", cat: "daily-life", note: "" },
  { id: "p485", es: "¿Hay lavandería cerca?", en: "Is there a laundromat nearby?", cat: "daily-life", note: "" },
  { id: "p486", es: "Necesito un corte de pelo.", en: "I need a haircut.", cat: "daily-life", note: "" },
  { id: "p487", es: "Voy al supermercado.", en: "I'm going to the supermarket.", cat: "daily-life", note: "" },
  { id: "p488", es: "¿Qué necesitamos de la tienda?", en: "What do we need from the store?", cat: "daily-life", note: "" },
  { id: "p489", es: "Se me olvidó.", en: "I forgot.", cat: "daily-life", note: "" },
  { id: "p490", es: "Se me olvidó la palabra.", en: "I forgot the word.", cat: "daily-life", note: "" },
  { id: "p491", es: "Dame un segundo.", en: "Give me a second.", cat: "daily-life", note: "informal" },
  { id: "p492", es: "¿Puedes repetir eso?", en: "Can you repeat that?", cat: "daily-life", note: "informal" },
  { id: "p493", es: "¿Cómo se pronuncia?", en: "How do you pronounce it?", cat: "daily-life", note: "" },
  { id: "p494", es: "¿Está bien dicho?", en: "Did I say that right?", cat: "daily-life", note: "" },
  { id: "p495", es: "El clima está raro hoy.", en: "The weather is weird today.", cat: "daily-life", note: "" },
  { id: "p496", es: "Va a llover.", en: "It's going to rain.", cat: "daily-life", note: "" },
  { id: "p497", es: "¿Viste las noticias?", en: "Did you see the news?", cat: "daily-life", note: "informal" },
  { id: "p498", es: "Mi teléfono está fallando.", en: "My phone is acting up.", cat: "daily-life", note: "" },
  { id: "p499", es: "¿Me mandas la dirección?", en: "Will you send me the address?", cat: "daily-life", note: "informal" },
  { id: "p500", es: "Te mando un mensaje.", en: "I'll text you.", cat: "daily-life", note: "informal" },
];
