// Hablo phrase library. Content only — no logic.
// Array order = unlock order. ids are stable forever; append, never renumber.
// Latin American Spanish; no vosotros. Validated by test/phrases.test.js.
window.PHRASES = [
  // ---- Tier 1: survival essentials (p001–p055) ----
  { id: "p001", es: "Hola, ¿cómo estás?", en: "Hi, how are you?", cat: "greetings-basics", note: "informal" },
  { id: "p002", es: "Bien, gracias. ¿Y tú?", en: "Good, thanks. And you?", cat: "greetings-basics", note: "" },
  { id: "p003", es: "Mucho gusto.", en: "Nice to meet you.", cat: "greetings-basics", note: "" },
  { id: "p004", es: "Por favor.", en: "Please.", cat: "courtesy", note: "" },
  { id: "p005", es: "Gracias.", en: "Thank you.", cat: "courtesy", note: "" },
  { id: "p006", es: "De nada.", en: "You're welcome.", cat: "courtesy", note: "" },
  { id: "p007", es: "Perdón, no entiendo.", en: "Sorry, I don't understand.", cat: "greetings-basics", note: "" },
  { id: "p008", es: "¿Puedes hablar más despacio?", en: "Can you speak more slowly?", cat: "greetings-basics", note: "" },
  { id: "p009", es: "¿Cómo se dice esto en español?", en: "How do you say this in Spanish?", cat: "greetings-basics", note: "" },
  { id: "p010", es: "No hablo mucho español.", en: "I don't speak much Spanish.", cat: "greetings-basics", note: "" },
  { id: "p011", es: "¿Dónde está el baño?", en: "Where is the bathroom?", cat: "getting-around", note: "" },
  { id: "p012", es: "¿Cuánto cuesta?", en: "How much does it cost?", cat: "money-shopping", note: "" },
  { id: "p013", es: "Quisiera esto, por favor.", en: "I'd like this, please.", cat: "food-restaurants", note: "polite" },
  { id: "p014", es: "La cuenta, por favor.", en: "The check, please.", cat: "food-restaurants", note: "" },
  { id: "p015", es: "No sé.", en: "I don't know.", cat: "questions-connectors", note: "" },
  { id: "p016", es: "Buenos días.", en: "Good morning.", cat: "greetings-basics", note: "" },
  { id: "p017", es: "Buenas tardes.", en: "Good afternoon.", cat: "greetings-basics", note: "" },
  { id: "p018", es: "Buenas noches.", en: "Good evening. / Good night.", cat: "greetings-basics", note: "" },
  { id: "p019", es: "Adiós, hasta luego.", en: "Goodbye, see you later.", cat: "greetings-basics", note: "" },
  { id: "p020", es: "¿Qué tal?", en: "How's it going?", cat: "greetings-basics", note: "informal" },
  { id: "p021", es: "Me llamo Andy.", en: "My name is Andy.", cat: "greetings-basics", note: "" },
  { id: "p022", es: "¿Cómo te llamas?", en: "What's your name?", cat: "greetings-basics", note: "informal" },
  { id: "p023", es: "¿Habla inglés?", en: "Do you speak English?", cat: "greetings-basics", note: "polite (usted)" },
  { id: "p024", es: "Disculpe.", en: "Excuse me. (to get attention)", cat: "courtesy", note: "polite (usted)" },
  { id: "p025", es: "Con permiso.", en: "Excuse me. (passing by)", cat: "courtesy", note: "" },
  { id: "p026", es: "Lo siento.", en: "I'm sorry.", cat: "courtesy", note: "" },
  { id: "p027", es: "No hay problema.", en: "No problem.", cat: "courtesy", note: "" },
  { id: "p028", es: "Muchas gracias, muy amable.", en: "Thanks so much, very kind of you.", cat: "courtesy", note: "" },
  { id: "p029", es: "¡Salud!", en: "Bless you! / Cheers!", cat: "courtesy", note: "" },
  { id: "p030", es: "Bienvenido.", en: "Welcome.", cat: "courtesy", note: "" },
  { id: "p031", es: "¿Dónde está la estación?", en: "Where is the station?", cat: "getting-around", note: "" },
  { id: "p032", es: "¿Está cerca?", en: "Is it close?", cat: "getting-around", note: "" },
  { id: "p033", es: "A la derecha.", en: "To the right.", cat: "getting-around", note: "" },
  { id: "p034", es: "A la izquierda.", en: "To the left.", cat: "getting-around", note: "" },
  { id: "p035", es: "Todo derecho.", en: "Straight ahead.", cat: "getting-around", note: "LatAm; also 'derecho'" },
  { id: "p036", es: "Una mesa para dos, por favor.", en: "A table for two, please.", cat: "food-restaurants", note: "" },
  { id: "p037", es: "El menú, por favor.", en: "The menu, please.", cat: "food-restaurants", note: "" },
  { id: "p038", es: "Un agua, por favor.", en: "A water, please.", cat: "food-restaurants", note: "" },
  { id: "p039", es: "Está delicioso.", en: "It's delicious.", cat: "food-restaurants", note: "" },
  { id: "p040", es: "¿Aceptan tarjeta?", en: "Do you take cards?", cat: "money-shopping", note: "" },
  { id: "p041", es: "En efectivo.", en: "In cash.", cat: "money-shopping", note: "" },
  { id: "p042", es: "Es muy caro.", en: "It's very expensive.", cat: "money-shopping", note: "" },
  { id: "p043", es: "Sí, claro.", en: "Yes, of course.", cat: "questions-connectors", note: "" },
  { id: "p044", es: "Tal vez.", en: "Maybe.", cat: "questions-connectors", note: "" },
  { id: "p045", es: "¿Por qué?", en: "Why?", cat: "questions-connectors", note: "" },
  { id: "p046", es: "Porque sí.", en: "Just because.", cat: "questions-connectors", note: "" },
  { id: "p047", es: "¿Qué es esto?", en: "What is this?", cat: "questions-connectors", note: "" },
  { id: "p048", es: "¡Ayuda!", en: "Help!", cat: "emergencies-help", note: "" },
  { id: "p049", es: "Necesito ayuda.", en: "I need help.", cat: "emergencies-help", note: "" },
  { id: "p050", es: "¿Me puede ayudar?", en: "Can you help me?", cat: "emergencies-help", note: "polite (usted)" },
  { id: "p051", es: "No me siento bien.", en: "I don't feel well.", cat: "emergencies-help", note: "" },
  { id: "p052", es: "Soy de Estados Unidos.", en: "I'm from the United States.", cat: "smalltalk-you", note: "" },
  { id: "p053", es: "¿De dónde eres?", en: "Where are you from?", cat: "smalltalk-you", note: "informal" },
  { id: "p054", es: "Estoy aprendiendo español.", en: "I'm learning Spanish.", cat: "smalltalk-you", note: "" },
  { id: "p055", es: "Vivo en Pensilvania.", en: "I live in Pennsylvania.", cat: "smalltalk-you", note: "" },
  // ---- Tier 2: high-frequency everyday (p056–p170) ----
  { id: "p056", es: "¿Cómo está usted?", en: "How are you?", cat: "greetings-basics", note: "formal (usted)" },
  { id: "p057", es: "¿Qué pasa?", en: "What's up?", cat: "greetings-basics", note: "informal" },
  { id: "p058", es: "Igualmente.", en: "Likewise.", cat: "greetings-basics", note: "" },
  { id: "p059", es: "Hasta mañana.", en: "See you tomorrow.", cat: "greetings-basics", note: "" },
  { id: "p060", es: "Nos vemos.", en: "See you.", cat: "greetings-basics", note: "informal" },
  { id: "p061", es: "Que tengas un buen día.", en: "Have a good day.", cat: "courtesy", note: "informal" },
  { id: "p062", es: "¿Todo bien?", en: "Everything good?", cat: "greetings-basics", note: "informal" },
  { id: "p063", es: "Tanto tiempo sin verte.", en: "Long time no see.", cat: "greetings-basics", note: "informal" },
  { id: "p064", es: "Con gusto.", en: "Gladly. / My pleasure.", cat: "courtesy", note: "common LatAm 'you're welcome'" },
  { id: "p065", es: "No se preocupe.", en: "Don't worry.", cat: "courtesy", note: "polite (usted)" },
  { id: "p066", es: "Está bien, no pasa nada.", en: "It's fine, no big deal.", cat: "courtesy", note: "" },
  { id: "p067", es: "¿Puedo pasar?", en: "May I come in / get by?", cat: "courtesy", note: "" },
  { id: "p068", es: "Es muy amable.", en: "That's very kind of you.", cat: "courtesy", note: "polite (usted)" },
  { id: "p069", es: "Perdón por llegar tarde.", en: "Sorry for being late.", cat: "courtesy", note: "" },
  { id: "p070", es: "¿Le molesta si abro la ventana?", en: "Do you mind if I open the window?", cat: "courtesy", note: "polite (usted)" },
  { id: "p071", es: "Gracias por todo.", en: "Thanks for everything.", cat: "courtesy", note: "" },
  { id: "p072", es: "¿A qué te dedicas?", en: "What do you do for work?", cat: "smalltalk-you", note: "informal" },
  { id: "p073", es: "Tengo mi propia empresa.", en: "I have my own company.", cat: "smalltalk-you", note: "" },
  { id: "p074", es: "¿Tienes hermanos?", en: "Do you have siblings?", cat: "smalltalk-you", note: "informal" },
  { id: "p075", es: "Tengo un hermano.", en: "I have one brother.", cat: "smalltalk-you", note: "" },
  { id: "p076", es: "¿Cuántos años tienes?", en: "How old are you?", cat: "smalltalk-you", note: "informal" },
  { id: "p077", es: "Tengo treinta años.", en: "I'm thirty years old.", cat: "smalltalk-you", note: "" },
  { id: "p078", es: "¿Qué te gusta hacer?", en: "What do you like to do?", cat: "smalltalk-you", note: "informal" },
  { id: "p079", es: "Me gusta viajar.", en: "I like to travel.", cat: "smalltalk-you", note: "" },
  { id: "p080", es: "Me gusta mucho la comida mexicana.", en: "I really like Mexican food.", cat: "smalltalk-you", note: "" },
  { id: "p081", es: "¿Estás casado?", en: "Are you married?", cat: "smalltalk-you", note: "informal; casada to a woman" },
  { id: "p082", es: "¿Hablas otros idiomas?", en: "Do you speak other languages?", cat: "smalltalk-you", note: "informal" },
  { id: "p083", es: "Es la primera vez que vengo aquí.", en: "It's my first time here.", cat: "smalltalk-you", note: "" },
  { id: "p084", es: "Pero…", en: "But…", cat: "questions-connectors", note: "" },
  { id: "p085", es: "Entonces…", en: "So… / Then…", cat: "questions-connectors", note: "" },
  { id: "p086", es: "También.", en: "Also. / Too.", cat: "questions-connectors", note: "" },
  { id: "p087", es: "Yo también.", en: "Me too.", cat: "questions-connectors", note: "" },
  { id: "p088", es: "Yo no.", en: "Not me.", cat: "questions-connectors", note: "" },
  { id: "p089", es: "O sea…", en: "I mean… / In other words…", cat: "questions-connectors", note: "filler" },
  { id: "p090", es: "Es que…", en: "The thing is…", cat: "questions-connectors", note: "filler" },
  { id: "p091", es: "¿Qué significa esa palabra?", en: "What does that word mean?", cat: "questions-connectors", note: "" },
  { id: "p092", es: "¿Cómo?", en: "What? / Come again?", cat: "questions-connectors", note: "" },
  { id: "p093", es: "¿Dónde?", en: "Where?", cat: "questions-connectors", note: "" },
  { id: "p094", es: "¿Cuándo?", en: "When?", cat: "questions-connectors", note: "" },
  { id: "p095", es: "¿Quién?", en: "Who?", cat: "questions-connectors", note: "" },
  { id: "p096", es: "¿Cuál prefieres?", en: "Which do you prefer?", cat: "questions-connectors", note: "informal" },
  { id: "p097", es: "Por ejemplo…", en: "For example…", cat: "questions-connectors", note: "" },
  { id: "p098", es: "Además…", en: "Besides… / What's more…", cat: "questions-connectors", note: "" },
  { id: "p099", es: "Casi.", en: "Almost.", cat: "questions-connectors", note: "" },
  { id: "p100", es: "¿Dónde puedo tomar un taxi?", en: "Where can I get a taxi?", cat: "getting-around", note: "" },
  { id: "p101", es: "¿Me puede llevar a esta dirección?", en: "Can you take me to this address?", cat: "getting-around", note: "polite (usted)" },
  { id: "p102", es: "Aquí está bien, gracias.", en: "Right here is fine, thanks.", cat: "getting-around", note: "in a taxi" },
  { id: "p103", es: "¿Cuánto tiempo se tarda?", en: "How long does it take?", cat: "getting-around", note: "" },
  { id: "p104", es: "¿A qué hora sale?", en: "What time does it leave?", cat: "getting-around", note: "" },
  { id: "p105", es: "¿Dónde está la parada del autobús?", en: "Where is the bus stop?", cat: "getting-around", note: "" },
  { id: "p106", es: "Un boleto, por favor.", en: "One ticket, please.", cat: "getting-around", note: "LatAm: boleto" },
  { id: "p107", es: "¿Este autobús va al centro?", en: "Does this bus go downtown?", cat: "getting-around", note: "" },
  { id: "p108", es: "Estoy perdido.", en: "I'm lost.", cat: "getting-around", note: "perdida for women" },
  { id: "p109", es: "¿Me puede mostrar en el mapa?", en: "Can you show me on the map?", cat: "getting-around", note: "polite (usted)" },
  { id: "p110", es: "¿Dónde está el aeropuerto?", en: "Where is the airport?", cat: "getting-around", note: "" },
  { id: "p111", es: "Está muy lejos.", en: "It's very far.", cat: "getting-around", note: "" },
  { id: "p112", es: "A dos cuadras.", en: "Two blocks away.", cat: "getting-around", note: "LatAm: cuadras" },
  { id: "p113", es: "En la esquina.", en: "On the corner.", cat: "getting-around", note: "" },
  { id: "p114", es: "¿Puedo ir caminando?", en: "Can I walk there?", cat: "getting-around", note: "" },
  { id: "p115", es: "¿Dónde estamos?", en: "Where are we?", cat: "getting-around", note: "" },
  { id: "p116", es: "Necesito un hotel.", en: "I need a hotel.", cat: "getting-around", note: "" },
  { id: "p117", es: "¿Tiene una habitación disponible?", en: "Do you have a room available?", cat: "getting-around", note: "polite (usted)" },
  { id: "p118", es: "Para mí, los tacos.", en: "For me, the tacos.", cat: "food-restaurants", note: "" },
  { id: "p119", es: "¿Qué me recomienda?", en: "What do you recommend?", cat: "food-restaurants", note: "polite (usted)" },
  { id: "p120", es: "Sin cebolla, por favor.", en: "Without onion, please.", cat: "food-restaurants", note: "" },
  { id: "p121", es: "Con todo.", en: "With everything.", cat: "food-restaurants", note: "" },
  { id: "p122", es: "Una cerveza, por favor.", en: "A beer, please.", cat: "food-restaurants", note: "" },
  { id: "p123", es: "Un café con leche.", en: "A coffee with milk.", cat: "food-restaurants", note: "" },
  { id: "p124", es: "¿Está picante?", en: "Is it spicy?", cat: "food-restaurants", note: "" },
  { id: "p125", es: "No muy picante, por favor.", en: "Not too spicy, please.", cat: "food-restaurants", note: "" },
  { id: "p126", es: "Soy alérgico a los mariscos.", en: "I'm allergic to shellfish.", cat: "food-restaurants", note: "alérgica for women" },
  { id: "p127", es: "¿Qué lleva este plato?", en: "What's in this dish?", cat: "food-restaurants", note: "" },
  { id: "p128", es: "¿Nos trae más agua, por favor?", en: "Would you bring us more water, please?", cat: "food-restaurants", note: "polite (usted)" },
  { id: "p129", es: "Está muy rico.", en: "It's really tasty.", cat: "food-restaurants", note: "very LatAm" },
  { id: "p130", es: "¿Está incluida la propina?", en: "Is the tip included?", cat: "food-restaurants", note: "" },
  { id: "p131", es: "Para llevar, por favor.", en: "To go, please.", cat: "food-restaurants", note: "" },
  { id: "p132", es: "Para comer aquí.", en: "For here.", cat: "food-restaurants", note: "" },
  { id: "p133", es: "¿Tienen menú en inglés?", en: "Do you have an English menu?", cat: "food-restaurants", note: "" },
  { id: "p134", es: "Buen provecho.", en: "Enjoy your meal.", cat: "food-restaurants", note: "" },
  { id: "p135", es: "Otra ronda, por favor.", en: "Another round, please.", cat: "food-restaurants", note: "" },
  { id: "p136", es: "¿Cuánto le debo?", en: "How much do I owe you?", cat: "money-shopping", note: "polite (usted)" },
  { id: "p137", es: "¿Tiene cambio?", en: "Do you have change?", cat: "money-shopping", note: "polite (usted)" },
  { id: "p138", es: "Quédese con el cambio.", en: "Keep the change.", cat: "money-shopping", note: "polite (usted)" },
  { id: "p139", es: "Solo estoy mirando.", en: "I'm just looking.", cat: "money-shopping", note: "shopping" },
  { id: "p140", es: "¿Tiene esto en otra talla?", en: "Do you have this in another size?", cat: "money-shopping", note: "" },
  { id: "p141", es: "¿Me hace un descuento?", en: "Can you give me a discount?", cat: "money-shopping", note: "" },
  { id: "p142", es: "Me lo llevo.", en: "I'll take it.", cat: "money-shopping", note: "" },
  { id: "p143", es: "¿Dónde hay un cajero?", en: "Where's an ATM?", cat: "money-shopping", note: "cajero automático" },
  { id: "p144", es: "¿A cómo está el dólar?", en: "What's the dollar exchange rate?", cat: "money-shopping", note: "LatAm" },
  { id: "p145", es: "Es demasiado.", en: "That's too much.", cat: "money-shopping", note: "" },
  { id: "p146", es: "¿Está en oferta?", en: "Is it on sale?", cat: "money-shopping", note: "" },
  { id: "p147", es: "Una bolsa, por favor.", en: "A bag, please.", cat: "money-shopping", note: "" },
  { id: "p148", es: "¿Qué hora es?", en: "What time is it?", cat: "time-plans", note: "" },
  { id: "p149", es: "¿A qué hora abren?", en: "What time do you open?", cat: "time-plans", note: "" },
  { id: "p150", es: "¿A qué hora cierran?", en: "What time do you close?", cat: "time-plans", note: "" },
  { id: "p151", es: "Hoy no puedo.", en: "I can't today.", cat: "time-plans", note: "" },
  { id: "p152", es: "¿Mañana te queda bien?", en: "Does tomorrow work for you?", cat: "time-plans", note: "informal" },
  { id: "p153", es: "Ahora mismo.", en: "Right now.", cat: "time-plans", note: "" },
  { id: "p154", es: "Ahorita vengo.", en: "I'll be right back.", cat: "time-plans", note: "very LatAm" },
  { id: "p155", es: "Más tarde.", en: "Later.", cat: "time-plans", note: "" },
  { id: "p156", es: "Ya voy.", en: "I'm coming. / On my way.", cat: "time-plans", note: "" },
  { id: "p157", es: "Todavía no.", en: "Not yet.", cat: "time-plans", note: "" },
  { id: "p158", es: "¿Estás listo?", en: "Are you ready?", cat: "time-plans", note: "informal; lista to a woman" },
  { id: "p159", es: "Estoy listo.", en: "I'm ready.", cat: "time-plans", note: "" },
  { id: "p160", es: "No tengo tiempo.", en: "I don't have time.", cat: "time-plans", note: "" },
  { id: "p161", es: "Tengo prisa.", en: "I'm in a hurry.", cat: "time-plans", note: "" },
  { id: "p162", es: "Sin prisa.", en: "No rush.", cat: "time-plans", note: "" },
  { id: "p163", es: "¿Cuál es la contraseña del wifi?", en: "What's the wifi password?", cat: "daily-life", note: "" },
  { id: "p164", es: "No tengo señal.", en: "I have no signal.", cat: "daily-life", note: "" },
  { id: "p165", es: "Se me acabó la batería.", en: "My battery died.", cat: "daily-life", note: "" },
  { id: "p166", es: "¿Me presta su cargador?", en: "Could I borrow your charger?", cat: "daily-life", note: "polite (usted)" },
  { id: "p167", es: "Hace mucho calor.", en: "It's really hot out.", cat: "daily-life", note: "" },
  { id: "p168", es: "Hace frío.", en: "It's cold out.", cat: "daily-life", note: "" },
  { id: "p169", es: "Está lloviendo.", en: "It's raining.", cat: "daily-life", note: "" },
  { id: "p170", es: "¡Qué bonito día!", en: "What a beautiful day!", cat: "daily-life", note: "" },
  // ---- Tier 3: real conversation (p171–p315) ----
  { id: "p171", es: "¿Tienes hijos?", en: "Do you have kids?", cat: "smalltalk-you", note: "informal" },
  { id: "p172", es: "Tengo una novia.", en: "I have a girlfriend.", cat: "smalltalk-you", note: "" },
  { id: "p173", es: "¿Qué hiciste el fin de semana?", en: "What did you do over the weekend?", cat: "smalltalk-you", note: "informal" },
  { id: "p174", es: "Fui a la playa.", en: "I went to the beach.", cat: "smalltalk-you", note: "" },
  { id: "p175", es: "¿Cuánto tiempo llevas aquí?", en: "How long have you been here?", cat: "smalltalk-you", note: "informal" },
  { id: "p176", es: "Llevo una semana aquí.", en: "I've been here a week.", cat: "smalltalk-you", note: "" },
  { id: "p177", es: "¿Te gusta vivir aquí?", en: "Do you like living here?", cat: "smalltalk-you", note: "informal" },
  { id: "p178", es: "Me encanta este lugar.", en: "I love this place.", cat: "smalltalk-you", note: "" },
  { id: "p179", es: "¿Haces ejercicio?", en: "Do you work out?", cat: "smalltalk-you", note: "informal" },
  { id: "p180", es: "Voy al gimnasio casi todos los días.", en: "I go to the gym almost every day.", cat: "smalltalk-you", note: "" },
  { id: "p181", es: "Me lastimé la rodilla.", en: "I hurt my knee.", cat: "smalltalk-you", note: "" },
  { id: "p182", es: "Estoy de vacaciones.", en: "I'm on vacation.", cat: "smalltalk-you", note: "" },
  { id: "p183", es: "Estoy aquí por trabajo.", en: "I'm here for work.", cat: "smalltalk-you", note: "" },
  { id: "p184", es: "¿Cuál es tu comida favorita?", en: "What's your favorite food?", cat: "smalltalk-you", note: "informal" },
  { id: "p185", es: "¿Ves fútbol?", en: "Do you watch soccer?", cat: "smalltalk-you", note: "informal" },
  { id: "p186", es: "Soy fanático de los deportes.", en: "I'm a big sports fan.", cat: "smalltalk-you", note: "" },
  { id: "p187", es: "¿Qué música te gusta?", en: "What music do you like?", cat: "smalltalk-you", note: "informal" },
  { id: "p188", es: "No conozco esa canción.", en: "I don't know that song.", cat: "smalltalk-you", note: "" },
  { id: "p189", es: "¿Conoces un buen lugar por aquí?", en: "Do you know a good spot around here?", cat: "smalltalk-you", note: "informal" },
  { id: "p190", es: "Te presento a mi amigo.", en: "Let me introduce you to my friend.", cat: "smalltalk-you", note: "informal" },
  { id: "p191", es: "¿Nos tomamos una foto?", en: "Should we take a photo?", cat: "smalltalk-you", note: "" },
  { id: "p192", es: "Dame tu número.", en: "Give me your number.", cat: "smalltalk-you", note: "informal" },
  { id: "p193", es: "Aunque…", en: "Although…", cat: "questions-connectors", note: "" },
  { id: "p194", es: "Sin embargo…", en: "However…", cat: "questions-connectors", note: "slightly formal" },
  { id: "p195", es: "De hecho…", en: "Actually… / In fact…", cat: "questions-connectors", note: "" },
  { id: "p196", es: "Por eso…", en: "That's why…", cat: "questions-connectors", note: "" },
  { id: "p197", es: "Así que…", en: "So…", cat: "questions-connectors", note: "" },
  { id: "p198", es: "Mientras tanto…", en: "Meanwhile…", cat: "questions-connectors", note: "" },
  { id: "p199", es: "En vez de eso…", en: "Instead of that…", cat: "questions-connectors", note: "" },
  { id: "p200", es: "Sobre todo…", en: "Above all… / Especially…", cat: "questions-connectors", note: "" },
  { id: "p201", es: "Depende.", en: "It depends.", cat: "questions-connectors", note: "" },
  { id: "p202", es: "Más o menos.", en: "More or less. / So-so.", cat: "questions-connectors", note: "" },
  { id: "p203", es: "Claro que sí.", en: "Of course.", cat: "questions-connectors", note: "" },
  { id: "p204", es: "Claro que no.", en: "Of course not.", cat: "questions-connectors", note: "" },
  { id: "p205", es: "¿Verdad?", en: "Right?", cat: "questions-connectors", note: "tag question" },
  { id: "p206", es: "A ver…", en: "Let's see…", cat: "questions-connectors", note: "" },
  { id: "p207", es: "Me parece que sí.", en: "I think so.", cat: "opinions-reactions", note: "" },
  { id: "p208", es: "Me parece que no.", en: "I don't think so.", cat: "opinions-reactions", note: "" },
  { id: "p209", es: "Estoy de acuerdo.", en: "I agree.", cat: "opinions-reactions", note: "" },
  { id: "p210", es: "No estoy de acuerdo.", en: "I don't agree.", cat: "opinions-reactions", note: "" },
  { id: "p211", es: "Tienes razón.", en: "You're right.", cat: "opinions-reactions", note: "informal" },
  { id: "p212", es: "Tiene sentido.", en: "That makes sense.", cat: "opinions-reactions", note: "" },
  { id: "p213", es: "¿En serio?", en: "Seriously? / Really?", cat: "opinions-reactions", note: "" },
  { id: "p214", es: "¡No me digas!", en: "You don't say! / No way!", cat: "opinions-reactions", note: "" },
  { id: "p215", es: "¡Qué bueno!", en: "That's great!", cat: "opinions-reactions", note: "" },
  { id: "p216", es: "¡Qué pena!", en: "What a shame!", cat: "opinions-reactions", note: "" },
  { id: "p217", es: "¡Qué raro!", en: "How strange!", cat: "opinions-reactions", note: "" },
  { id: "p218", es: "Vale la pena.", en: "It's worth it.", cat: "opinions-reactions", note: "" },
  { id: "p219", es: "No vale la pena.", en: "It's not worth it.", cat: "opinions-reactions", note: "" },
  { id: "p220", es: "Me da igual.", en: "I don't care either way.", cat: "opinions-reactions", note: "" },
  { id: "p221", es: "¿Qué opinas?", en: "What do you think?", cat: "opinions-reactions", note: "informal" },
  { id: "p222", es: "¿Qué te pareció?", en: "What did you think of it?", cat: "opinions-reactions", note: "informal" },
  { id: "p223", es: "Me gustó mucho.", en: "I liked it a lot.", cat: "opinions-reactions", note: "" },
  { id: "p224", es: "No me gustó para nada.", en: "I didn't like it at all.", cat: "opinions-reactions", note: "" },
  { id: "p225", es: "Es mi favorito.", en: "It's my favorite.", cat: "opinions-reactions", note: "" },
  { id: "p226", es: "Está increíble.", en: "It's incredible.", cat: "opinions-reactions", note: "" },
  { id: "p227", es: "Podría ser mejor.", en: "It could be better.", cat: "opinions-reactions", note: "" },
  { id: "p228", es: "Fue una buena idea.", en: "It was a good idea.", cat: "opinions-reactions", note: "" },
  { id: "p229", es: "Tengo hambre.", en: "I'm hungry.", cat: "feelings-states", note: "" },
  { id: "p230", es: "Tengo sed.", en: "I'm thirsty.", cat: "feelings-states", note: "" },
  { id: "p231", es: "Tengo sueño.", en: "I'm sleepy.", cat: "feelings-states", note: "" },
  { id: "p232", es: "Tengo frío.", en: "I'm cold.", cat: "feelings-states", note: "" },
  { id: "p233", es: "Tengo calor.", en: "I'm hot.", cat: "feelings-states", note: "" },
  { id: "p234", es: "Estoy cansado.", en: "I'm tired.", cat: "feelings-states", note: "cansada for women" },
  { id: "p235", es: "Estoy emocionado.", en: "I'm excited.", cat: "feelings-states", note: "" },
  { id: "p236", es: "Estoy nervioso.", en: "I'm nervous.", cat: "feelings-states", note: "" },
  { id: "p237", es: "Estoy aburrido.", en: "I'm bored.", cat: "feelings-states", note: "" },
  { id: "p238", es: "Estoy ocupado.", en: "I'm busy.", cat: "feelings-states", note: "" },
  { id: "p239", es: "Estoy relajado.", en: "I'm relaxed.", cat: "feelings-states", note: "" },
  { id: "p240", es: "Me duele la cabeza.", en: "My head hurts.", cat: "feelings-states", note: "" },
  { id: "p241", es: "Me duele el estómago.", en: "My stomach hurts.", cat: "feelings-states", note: "" },
  { id: "p242", es: "Estoy enfermo.", en: "I'm sick.", cat: "feelings-states", note: "" },
  { id: "p243", es: "Me siento mucho mejor.", en: "I feel much better.", cat: "feelings-states", note: "" },
  { id: "p244", es: "Estoy feliz.", en: "I'm happy.", cat: "feelings-states", note: "" },
  { id: "p245", es: "Estoy un poco triste.", en: "I'm a little sad.", cat: "feelings-states", note: "" },
  { id: "p246", es: "No estoy de humor.", en: "I'm not in the mood.", cat: "feelings-states", note: "" },
  { id: "p247", es: "¿Tienen opciones vegetarianas?", en: "Do you have vegetarian options?", cat: "food-restaurants", note: "" },
  { id: "p248", es: "Quisiera reservar una mesa.", en: "I'd like to reserve a table.", cat: "food-restaurants", note: "" },
  { id: "p249", es: "¿Cuánto es la espera?", en: "How long is the wait?", cat: "food-restaurants", note: "" },
  { id: "p250", es: "Mi plato está frío.", en: "My dish is cold.", cat: "food-restaurants", note: "" },
  { id: "p251", es: "Esto no es lo que pedí.", en: "This isn't what I ordered.", cat: "food-restaurants", note: "" },
  { id: "p252", es: "¿Me trae la carta de vinos?", en: "Can I see the wine list?", cat: "food-restaurants", note: "polite (usted)" },
  { id: "p253", es: "Un vino tinto, por favor.", en: "A red wine, please.", cat: "food-restaurants", note: "" },
  { id: "p254", es: "Una botella de agua sin gas.", en: "A bottle of still water.", cat: "food-restaurants", note: "" },
  { id: "p255", es: "Con hielo, por favor.", en: "With ice, please.", cat: "food-restaurants", note: "" },
  { id: "p256", es: "Sin hielo, por favor.", en: "Without ice, please.", cat: "food-restaurants", note: "" },
  { id: "p257", es: "¿Qué postres tienen?", en: "What desserts do you have?", cat: "food-restaurants", note: "" },
  { id: "p258", es: "Estoy lleno.", en: "I'm full.", cat: "food-restaurants", note: "llena for women" },
  { id: "p259", es: "Todo estuvo excelente.", en: "Everything was excellent.", cat: "food-restaurants", note: "" },
  { id: "p260", es: "¿Puedo pagar con el teléfono?", en: "Can I pay with my phone?", cat: "food-restaurants", note: "" },
  { id: "p261", es: "¿Nos cobra por separado?", en: "Separate checks, please?", cat: "food-restaurants", note: "polite (usted)" },
  { id: "p262", es: "Es para compartir.", en: "It's to share.", cat: "food-restaurants", note: "" },
  { id: "p263", es: "¿A qué hora sirven el desayuno?", en: "What time do you serve breakfast?", cat: "food-restaurants", note: "" },
  { id: "p264", es: "¿Está incluido el desayuno?", en: "Is breakfast included?", cat: "food-restaurants", note: "" },
  { id: "p265", es: "¿Me puede pedir un taxi?", en: "Can you call me a taxi?", cat: "getting-around", note: "polite (usted)" },
  { id: "p266", es: "Voy a mi hotel.", en: "I'm going to my hotel.", cat: "getting-around", note: "" },
  { id: "p267", es: "Pare aquí, por favor.", en: "Stop here, please.", cat: "getting-around", note: "polite (usted)" },
  { id: "p268", es: "Siga derecho, por favor.", en: "Keep going straight, please.", cat: "getting-around", note: "polite (usted)" },
  { id: "p269", es: "¿Cuál es la mejor manera de llegar?", en: "What's the best way to get there?", cat: "getting-around", note: "" },
  { id: "p270", es: "¿Hay mucho tráfico?", en: "Is there a lot of traffic?", cat: "getting-around", note: "" },
  { id: "p271", es: "Perdí mi vuelo.", en: "I missed my flight.", cat: "getting-around", note: "" },
  { id: "p272", es: "¿Dónde recojo mi equipaje?", en: "Where do I pick up my luggage?", cat: "getting-around", note: "" },
  { id: "p273", es: "Mi maleta se perdió.", en: "My suitcase got lost.", cat: "getting-around", note: "" },
  { id: "p274", es: "¿Dónde está la salida?", en: "Where is the exit?", cat: "getting-around", note: "" },
  { id: "p275", es: "¿Dónde está la entrada?", en: "Where is the entrance?", cat: "getting-around", note: "" },
  { id: "p276", es: "Estoy buscando esta dirección.", en: "I'm looking for this address.", cat: "getting-around", note: "" },
  { id: "p277", es: "¿Me deja en la esquina?", en: "Can you drop me at the corner?", cat: "getting-around", note: "polite (usted)" },
  { id: "p278", es: "La próxima parada.", en: "The next stop.", cat: "getting-around", note: "" },
  { id: "p279", es: "¿Cuál es el precio final?", en: "What's the final price?", cat: "money-shopping", note: "" },
  { id: "p280", es: "¿Me da un recibo?", en: "Can I get a receipt?", cat: "money-shopping", note: "polite (usted)" },
  { id: "p281", es: "Me cobraron de más.", en: "They overcharged me.", cat: "money-shopping", note: "" },
  { id: "p282", es: "¿Puedo devolver esto?", en: "Can I return this?", cat: "money-shopping", note: "" },
  { id: "p283", es: "No funciona.", en: "It doesn't work.", cat: "money-shopping", note: "" },
  { id: "p284", es: "¿Tiene garantía?", en: "Does it have a warranty?", cat: "money-shopping", note: "" },
  { id: "p285", es: "Quiero cambiar dólares.", en: "I want to exchange dollars.", cat: "money-shopping", note: "" },
  { id: "p286", es: "¿Cuánto es en dólares?", en: "How much is that in dollars?", cat: "money-shopping", note: "" },
  { id: "p287", es: "Es una ganga.", en: "It's a bargain.", cat: "money-shopping", note: "" },
  { id: "p288", es: "¿Me lo puede envolver?", en: "Can you wrap it for me?", cat: "money-shopping", note: "polite (usted)" },
  { id: "p289", es: "¿Hay que pagar por adelantado?", en: "Do you have to pay in advance?", cat: "money-shopping", note: "" },
  { id: "p290", es: "Ya pagué.", en: "I already paid.", cat: "money-shopping", note: "" },
  { id: "p291", es: "¿Qué vas a hacer mañana?", en: "What are you doing tomorrow?", cat: "time-plans", note: "informal" },
  { id: "p292", es: "Vamos a salir esta noche.", en: "We're going out tonight.", cat: "time-plans", note: "" },
  { id: "p293", es: "¿Quieres venir con nosotros?", en: "Do you want to come with us?", cat: "time-plans", note: "informal" },
  { id: "p294", es: "Nos vemos a las ocho.", en: "See you at eight.", cat: "time-plans", note: "" },
  { id: "p295", es: "Llego en cinco minutos.", en: "I'll be there in five minutes.", cat: "time-plans", note: "" },
  { id: "p296", es: "Voy tarde.", en: "I'm running late.", cat: "time-plans", note: "" },
  { id: "p297", es: "Llegaste temprano.", en: "You're early.", cat: "time-plans", note: "informal" },
  { id: "p298", es: "¿Cuándo vuelves?", en: "When are you coming back?", cat: "time-plans", note: "informal" },
  { id: "p299", es: "Vuelvo la próxima semana.", en: "I'm coming back next week.", cat: "time-plans", note: "" },
  { id: "p300", es: "El lunes que viene.", en: "Next Monday.", cat: "time-plans", note: "" },
  { id: "p301", es: "Todos los días.", en: "Every day.", cat: "time-plans", note: "" },
  { id: "p302", es: "De vez en cuando.", en: "Once in a while.", cat: "time-plans", note: "" },
  { id: "p303", es: "Casi nunca.", en: "Almost never.", cat: "time-plans", note: "" },
  { id: "p304", es: "Casi siempre.", en: "Almost always.", cat: "time-plans", note: "" },
  { id: "p305", es: "Fue un día largo.", en: "It was a long day.", cat: "time-plans", note: "" },
  { id: "p306", es: "Necesito un médico.", en: "I need a doctor.", cat: "emergencies-help", note: "" },
  { id: "p307", es: "Llame a una ambulancia.", en: "Call an ambulance.", cat: "emergencies-help", note: "polite (usted)" },
  { id: "p308", es: "Llame a la policía.", en: "Call the police.", cat: "emergencies-help", note: "polite (usted)" },
  { id: "p309", es: "Es una emergencia.", en: "It's an emergency.", cat: "emergencies-help", note: "" },
  { id: "p310", es: "Me robaron.", en: "I got robbed.", cat: "emergencies-help", note: "" },
  { id: "p311", es: "Perdí mi pasaporte.", en: "I lost my passport.", cat: "emergencies-help", note: "" },
  { id: "p312", es: "Perdí mi teléfono.", en: "I lost my phone.", cat: "emergencies-help", note: "" },
  { id: "p313", es: "¿Dónde está la farmacia más cercana?", en: "Where's the nearest pharmacy?", cat: "emergencies-help", note: "" },
  { id: "p314", es: "Necesito medicina para el dolor.", en: "I need pain medicine.", cat: "emergencies-help", note: "" },
  { id: "p315", es: "Tenga cuidado.", en: "Be careful.", cat: "emergencies-help", note: "polite (usted)" },
];
